// Western 1870s Weapons — extracted from project docs (Down Darker Trails style summary)
// Reuses the 1920s WeaponRec shape so we can feed the same mapper
import type { WeaponRec } from '../classic-1920s/weapons-data';

function dollars(n: number | null) {
  return { c1920s: n, modern: null } as { c1920s: number | null; modern: number | null };
}

const BOOK = 'Down Darker Trails';

export const WEAPONS_WESTERN_1870S: WeaponRec[] = [
  // Revolvers (Firearms Handgun)
  { name: '.31 Colt Pocket', skill: 'Firearms', specialization: 'Handgun', damage: '1D8', base_range: '10 yards', base_range_yards: 10, uses_per_round: '1 (3)', uses_per_round_int: 1, mag: '5', mag_int: 5, cost: dollars(9), malfunction: '99', eras: ['Western 1870s'], category: 'Revolvers', source: { book: BOOK, page: null } },
  { name: '.44 Colt Dragoon', skill: 'Firearms', specialization: 'Handgun', damage: '1D10+2', base_range: '15 yards', base_range_yards: 15, uses_per_round: '1 (3)', uses_per_round_int: 1, mag: '6', mag_int: 6, cost: dollars(6), malfunction: '99', eras: ['Western 1870s'], category: 'Revolvers', source: { book: BOOK, page: null } },
  { name: '.42/20 gauge LeMat Pistol', skill: 'Firearms', specialization: 'Handgun', damage: '1D10+1 (2D6/1D6/1D3)', base_range: '15 (10/20/50) yards', base_range_yards: 15, uses_per_round: '1 (3)', uses_per_round_int: 1, mag: '9 (1)', mag_int: 9, cost: dollars(17), malfunction: '99', eras: ['Western 1870s'], category: 'Revolvers', source: { book: BOOK, page: null } },
  { name: '.22 Smith & Wesson Model 1', skill: 'Firearms', specialization: 'Handgun', damage: '1D6', base_range: '15 yards', base_range_yards: 15, uses_per_round: '1 (3)', uses_per_round_int: 1, mag: '7', mag_int: 7, cost: dollars(6), malfunction: '99', eras: ['Western 1870s'], category: 'Revolvers', source: { book: BOOK, page: null } },
  { name: '.44 Colt Army', skill: 'Firearms', specialization: 'Handgun', damage: '1D10+2', base_range: '15 yards', base_range_yards: 15, uses_per_round: '1 (3)', uses_per_round_int: 1, mag: '6', mag_int: 6, cost: dollars(14), malfunction: '99', eras: ['Western 1870s'], category: 'Revolvers', source: { book: BOOK, page: null } },
  { name: '.36 Colt Navy', skill: 'Firearms', specialization: 'Handgun', damage: '1D8', base_range: '15 yards', base_range_yards: 15, uses_per_round: '1 (3)', uses_per_round_int: 1, mag: '6', mag_int: 6, cost: dollars(6), malfunction: '99', eras: ['Western 1870s'], category: 'Revolvers', source: { book: BOOK, page: null } },
  { name: '.36 Colt Police', skill: 'Firearms', specialization: 'Handgun', damage: '1D8', base_range: '15 yards', base_range_yards: 15, uses_per_round: '1 (3)', uses_per_round_int: 1, mag: '5', mag_int: 5, cost: dollars(10), malfunction: '99', eras: ['Western 1870s'], category: 'Revolvers', source: { book: BOOK, page: null } },
  { name: '.32 Smith & Wesson Model 2', skill: 'Firearms', specialization: 'Handgun', damage: '1D6+1', base_range: '15 yards', base_range_yards: 15, uses_per_round: '1 (3)', uses_per_round_int: 1, mag: '6', mag_int: 6, cost: dollars(10), malfunction: '99', eras: ['Western 1870s'], category: 'Revolvers', source: { book: BOOK, page: null } },
  { name: '.45 Colt Peacemaker', skill: 'Firearms', specialization: 'Handgun', damage: '1D10+2', base_range: '15 yards', base_range_yards: 15, uses_per_round: '1 (3)', uses_per_round_int: 1, mag: '6', mag_int: 6, cost: dollars(10), malfunction: '99', eras: ['Western 1870s'], category: 'Revolvers', source: { book: BOOK, page: null } },
  { name: '44–40 Remington', skill: 'Firearms', specialization: 'Handgun', damage: '1D10+2', base_range: '15 yards', base_range_yards: 15, uses_per_round: '1 (3)', uses_per_round_int: 1, mag: '6', mag_int: 6, cost: dollars(15), malfunction: '99', eras: ['Western 1870s'], category: 'Revolvers', source: { book: BOOK, page: null } },
  { name: '.45 Smith & Wesson Schofield', skill: 'Firearms', specialization: 'Handgun', damage: '1D10+2', base_range: '15 yards', base_range_yards: 15, uses_per_round: '1 (3)', uses_per_round_int: 1, mag: '6', mag_int: 6, cost: dollars(13), malfunction: '99', eras: ['Western 1870s'], category: 'Revolvers', source: { book: BOOK, page: null } },

  // Holdout Weapons
  { name: '.44 Derringer', skill: 'Firearms', specialization: 'Handgun', damage: '1D10+2', base_range: '3 yards', base_range_yards: 3, uses_per_round: '1', uses_per_round_int: 1, mag: '1 or 3', mag_int: null, cost: dollars(2), malfunction: '99', eras: ['Western 1870s'], category: 'Holdout Weapons (one-shots)', source: { book: BOOK, page: null } },
  { name: '.41 Colt 1-shot', skill: 'Firearms', specialization: 'Handgun', damage: '1D10+1', base_range: '3 yards', base_range_yards: 3, uses_per_round: '1', uses_per_round_int: 1, mag: '1', mag_int: 1, cost: dollars(3), malfunction: '99', eras: ['Western 1870s'], category: 'Holdout Weapons (one-shots)', source: { book: BOOK, page: null } },
  { name: '.41 Remington 2-shot', skill: 'Firearms', specialization: 'Handgun', damage: '1D10+1', base_range: '3 yards', base_range_yards: 3, uses_per_round: '1 (2)', uses_per_round_int: 1, mag: '2', mag_int: 2, cost: dollars(5), malfunction: '99', eras: ['Western 1870s'], category: 'Holdout Weapons (one-shots)', source: { book: BOOK, page: null } },
  { name: '.41 Colt Cloverleaf', skill: 'Firearms', specialization: 'Handgun', damage: '1D10+1', base_range: '3 yards', base_range_yards: 3, uses_per_round: '1', uses_per_round_int: 1, mag: '4', mag_int: 4, cost: dollars(9), malfunction: '99', eras: ['Western 1870s'], category: 'Holdout Weapons (one-shots)', source: { book: BOOK, page: null } },
  { name: '.32 or .22 Remington Rifle Cane', skill: 'Firearms', specialization: 'Rifle/Shotgun', damage: '1D8 or 1D6', base_range: '15 yards', base_range_yards: 15, uses_per_round: '1', uses_per_round_int: 1, mag: '1 or 3', mag_int: null, cost: dollars(10), malfunction: '98', eras: ['Western 1870s'], category: 'Holdout Weapons (one-shots)', source: { book: BOOK, page: null } },

  // Rifles
  { name: '.50 Hawken Plains Rifle', skill: 'Firearms', specialization: 'Rifle/Shotgun', damage: '2D6+4', base_range: '60 yards', base_range_yards: 60, uses_per_round: '1/4', uses_per_round_int: null, mag: '1', mag_int: 1, cost: dollars(5), malfunction: '98', eras: ['Western 1870s'], category: 'Rifles', source: { book: BOOK, page: null } },
  { name: '.52 Sharps Rifle', skill: 'Firearms', specialization: 'Rifle/Shotgun', damage: '2D6+2', base_range: '80 yards', base_range_yards: 80, uses_per_round: '1/3', uses_per_round_int: null, mag: '1', mag_int: 1, cost: dollars(12), malfunction: '98', eras: ['Western 1870s'], category: 'Rifles', source: { book: BOOK, page: null } },
  { name: '.52 Sharps Carbine', skill: 'Firearms', specialization: 'Rifle/Shotgun', damage: '2D6+2', base_range: '50 yards', base_range_yards: 50, uses_per_round: '1/3', uses_per_round_int: null, mag: '1', mag_int: 1, cost: dollars(11), malfunction: '98', eras: ['Western 1870s'], category: 'Rifles', source: { book: BOOK, page: null } },
  { name: '.58 Springfield Rifle', skill: 'Firearms', specialization: 'Rifle/Shotgun', damage: '1D10+4', base_range: '60 yards', base_range_yards: 60, uses_per_round: '1/4', uses_per_round_int: null, mag: '1', mag_int: 1, cost: dollars(10), malfunction: '95', eras: ['Western 1870s'], category: 'Rifles', source: { book: BOOK, page: null } },
  { name: '.44 Henry', skill: 'Firearms', specialization: 'Rifle/Shotgun', damage: '2D6+1', base_range: '80 yards', base_range_yards: 80, uses_per_round: '1', uses_per_round_int: 1, mag: '16', mag_int: 16, cost: dollars(17), malfunction: '98', eras: ['Western 1870s'], category: 'Rifles', source: { book: BOOK, page: null } },
  { name: '.56 Spencer Carbine', skill: 'Firearms', specialization: 'Rifle/Shotgun', damage: '2D6+3', base_range: '50 yards', base_range_yards: 50, uses_per_round: '1', uses_per_round_int: 1, mag: '8', mag_int: 8, cost: dollars(18), malfunction: '98', eras: ['Western 1870s'], category: 'Rifles', source: { book: BOOK, page: null } },
  { name: '.50–70 Springfield Trapdoor', skill: 'Firearms', specialization: 'Rifle/Shotgun', damage: '2D6+4', base_range: '90 yards', base_range_yards: 90, uses_per_round: '1/3', uses_per_round_int: null, mag: '1', mag_int: 1, cost: dollars(12), malfunction: '99', eras: ['Western 1870s'], category: 'Rifles', source: { book: BOOK, page: null } },
  { name: '.45–70 Springfield Trapdoor', skill: 'Firearms', specialization: 'Rifle/Shotgun', damage: '2D6+2', base_range: '100 yards', base_range_yards: 100, uses_per_round: '1/3', uses_per_round_int: null, mag: '1', mag_int: 1, cost: dollars(12), malfunction: '99', eras: ['Western 1870s'], category: 'Rifles', source: { book: BOOK, page: null } },
  { name: ".44–40 Winchester ’73 Rifle (or Carbine)", skill: 'Firearms', specialization: 'Rifle/Shotgun', damage: '2D6+1', base_range: '80 or 50 yards', base_range_yards: null, uses_per_round: '1', uses_per_round_int: 1, mag: '18 (7)', mag_int: 18, cost: dollars(20), malfunction: '98', eras: ['Western 1870s'], category: 'Rifles', source: { book: BOOK, page: null } },
  { name: 'Sharps “Big 50”', skill: 'Firearms', specialization: 'Rifle/Shotgun', damage: '3D6', base_range: '100 yards', base_range_yards: 100, uses_per_round: '1/3', uses_per_round_int: null, mag: '1', mag_int: 1, cost: dollars(17), malfunction: '99', eras: ['Western 1870s'], category: 'Rifles', source: { book: BOOK, page: null } },
  { name: ".45 Winchester ’76 Rifle (or Carbine)", skill: 'Firearms', specialization: 'Rifle/Shotgun', damage: '2D6+3', base_range: '80 (50) yards', base_range_yards: null, uses_per_round: '1', uses_per_round_int: 1, mag: '14 (17)', mag_int: 14, cost: dollars(22), malfunction: '98', eras: ['Western 1870s'], category: 'Rifles', source: { book: BOOK, page: null } },

  // Shotguns
  { name: '10‑gauge Shotgun shot (or slug)', skill: 'Firearms', specialization: 'Rifle/Shotgun', damage: '4D6+2/2D6+1/1D4 (1D10+7)', base_range: '10/20/50 (or 50) yards', base_range_yards: null, uses_per_round: '1 or 2', uses_per_round_int: null, mag: '2', mag_int: 2, cost: dollars(25), malfunction: '99', eras: ['Western 1870s'], category: 'Shotguns', source: { book: BOOK, page: null } },
  { name: '12‑gauge Shotgun heavy shot (or slug)', skill: 'Firearms', specialization: 'Rifle/Shotgun', damage: '4D6/2D6/1D6 (1D10+6)', base_range: '10/20/50 (or 50) yards', base_range_yards: null, uses_per_round: '1 or 2', uses_per_round_int: null, mag: '2', mag_int: 2, cost: dollars(30), malfunction: '99', eras: ['Western 1870s'], category: 'Shotguns', source: { book: BOOK, page: null } },
  { name: '16‑gauge Shotgun heavy shot (or slug)', skill: 'Firearms', specialization: 'Rifle/Shotgun', damage: '2D6+2/1D6+1/1D4 (1D10+5)', base_range: '10/20/50 (or 50) yards', base_range_yards: null, uses_per_round: '1 or 2', uses_per_round_int: null, mag: '2', mag_int: 2, cost: dollars(35), malfunction: '99', eras: ['Western 1870s'], category: 'Shotguns', source: { book: BOOK, page: null } },
  { name: '20‑gauge Shotgun heavy shot (or slug)', skill: 'Firearms', specialization: 'Rifle/Shotgun', damage: '2D6/1D6/1D3 (1D10+4)', base_range: '10/20/50 (or 50) yards', base_range_yards: null, uses_per_round: '1 or 2', uses_per_round_int: null, mag: '2', mag_int: 2, cost: dollars(40), malfunction: '99', eras: ['Western 1870s'], category: 'Shotguns', source: { book: BOOK, page: null } },

  // Heavy Weapons & Explosives
  { name: '.58 Gatling Gun', skill: 'Firearms', specialization: 'Machine Gun', damage: '2D6+4', base_range: '100 yards', base_range_yards: 100, uses_per_round: 'Full Auto', uses_per_round_int: null, mag: '200 (mag)', mag_int: 200, cost: dollars(120), malfunction: '95', eras: ['Western 1870s'], category: 'Heavy Weapons, Explosives', source: { book: BOOK, page: null } },
  { name: 'Dynamite (per stick)', skill: 'Demolitions or Throw', specialization: null, damage: '4D10 3 yards', base_range: 'STR feet', base_range_yards: null, uses_per_round: '1/2', uses_per_round_int: null, mag: '1', mag_int: 1, cost: dollars(0.25), malfunction: '98', eras: ['Western 1870s'], category: 'Heavy Weapons, Explosives', source: { book: BOOK, page: null } },
  { name: 'Incendiary Device', skill: 'Throw', specialization: null, damage: '2D6+burn', base_range: 'STR feet', base_range_yards: null, uses_per_round: '1/2', uses_per_round_int: null, mag: '1', mag_int: 1, cost: dollars(null), malfunction: '95', eras: ['Western 1870s'], category: 'Heavy Weapons, Explosives', source: { book: BOOK, page: null } },

  // Melee Weapons
  { name: 'Arkansas Toothpick', skill: 'Fighting', specialization: 'Brawl', damage: '1D6+DB', base_range: 'Touch', base_range_yards: null, uses_per_round: '1', uses_per_round_int: 1, mag: '-', mag_int: null, cost: dollars(2), malfunction: 'N/A', eras: ['Western 1870s'], category: 'Melee Weapons', source: { book: BOOK, page: null } },
  { name: 'Axe', skill: 'Fighting', specialization: 'Axe', damage: '1D8+2+DB', base_range: 'Touch', base_range_yards: null, uses_per_round: '1', uses_per_round_int: 1, mag: '-', mag_int: null, cost: dollars(3), malfunction: 'N/A', eras: ['Western 1870s'], category: 'Melee Weapons', source: { book: BOOK, page: null } },
  { name: 'Bow and Arrows', skill: 'Firearms', specialization: 'Bow', damage: '1D6+½DB', base_range: '30 yards', base_range_yards: 30, uses_per_round: '1', uses_per_round_int: 1, mag: '-', mag_int: null, cost: dollars(null), malfunction: '97', eras: ['Western 1870s'], category: 'Melee Weapons', source: { book: BOOK, page: null } },
  { name: 'Bowie Knife', skill: 'Fighting', specialization: 'Brawl', damage: '1D4+2+DB', base_range: 'Touch', base_range_yards: null, uses_per_round: '1', uses_per_round_int: 1, mag: '-', mag_int: null, cost: dollars(2), malfunction: 'N/A', eras: ['Western 1870s'], category: 'Melee Weapons', source: { book: BOOK, page: null } },
  { name: 'Burning Torch', skill: 'Fighting', specialization: 'Brawl', damage: '1D6+burn', base_range: 'Touch', base_range_yards: null, uses_per_round: '1', uses_per_round_int: 1, mag: '-', mag_int: null, cost: dollars(null), malfunction: 'N/A', eras: ['Western 1870s'], category: 'Melee Weapons', source: { book: BOOK, page: null } },
  { name: 'Cavalry Saber', skill: 'Fighting', specialization: 'Sword', damage: '1D8+1+DB', base_range: 'Touch', base_range_yards: null, uses_per_round: '1', uses_per_round_int: 1, mag: '-', mag_int: null, cost: dollars(5), malfunction: 'N/A', eras: ['Western 1870s'], category: 'Melee Weapons', source: { book: BOOK, page: null } },
  { name: 'Club (large)', skill: 'Fighting', specialization: 'Brawl', damage: '1D8+DB', base_range: 'Touch', base_range_yards: null, uses_per_round: '1', uses_per_round_int: 1, mag: '-', mag_int: null, cost: dollars(null), malfunction: 'N/A', eras: ['Western 1870s'], category: 'Melee Weapons', source: { book: BOOK, page: null } },
  { name: 'Lasso', skill: 'Rope Use or Throw', specialization: null, damage: 'entangle', base_range: '5 yards', base_range_yards: 5, uses_per_round: '1', uses_per_round_int: 1, mag: '-', mag_int: null, cost: dollars(null), malfunction: '100', eras: ['Western 1870s'], category: 'Melee Weapons', source: { book: BOOK, page: null } },
  { name: 'Spear/Bayonet', skill: 'Fighting or Throw', specialization: 'Spear/Brawl', damage: '1D8+1+DB', base_range: 'Touch or STR yards', base_range_yards: null, uses_per_round: '1', uses_per_round_int: 1, mag: '-', mag_int: null, cost: dollars(2), malfunction: 'N/A', eras: ['Western 1870s'], category: 'Melee Weapons', source: { book: BOOK, page: null } },
  { name: 'Tomahawk', skill: 'Fighting or Throw', specialization: 'Brawl', damage: '1D6+1+DB', base_range: 'Touch', base_range_yards: null, uses_per_round: '1', uses_per_round_int: 1, mag: '-', mag_int: null, cost: dollars(null), malfunction: 'N/A', eras: ['Western 1870s'], category: 'Melee Weapons', source: { book: BOOK, page: null } },
  { name: 'Whip', skill: 'Fighting', specialization: 'Whip', damage: '1D3+½DB, or entangle', base_range: '10 yards', base_range_yards: 10, uses_per_round: '1', uses_per_round_int: 1, mag: '-', mag_int: null, cost: dollars(5), malfunction: '100', eras: ['Western 1870s'], category: 'Melee Weapons', source: { book: BOOK, page: null } },
];
