// occupation-data.ts
import type { Occupation, OccupationGroup } from './types';

// NOTE: This data is adapted from Delta Green professions as a placeholder.
// The skill points formulas and credit ratings are examples and should be
// updated with official Call of Cthulhu occupation data.
export const OCCUPATIONS: Occupation[] = [
    {
        name: 'Anthropologist or Historian',
        description: 'You study humanity, sifting myth from history and understanding the patterns of culture over time.',
        group: 'Academic',
        skillPoints: 'EDU × 4',
        creditRatingRange: { min: 20, max: 50 },
        occupationalSkills: [ 'Anthropology', 'Archaeology', 'History', 'Library Use', 'Occult', 'Other Language', 'Persuade', 'Spot Hidden' ],
        source: "Adapted from Delta Green",
        archetypicalClothing: "tweed suit or rugged field clothes, sturdy boots, satchel with notebooks",
    },
    {
        name: 'Computer Scientist or Engineer',
        description: 'You are a craftsman with data or machinery, building and breaking the digital backbone of the modern world.',
        group: 'Professional',
        skillPoints: 'EDU × 4',
        creditRatingRange: { min: 30, max: 70 },
        occupationalSkills: [ 'Computer Use', 'Electrical Repair', 'Electronics', 'Library Use', 'Mechanical Repair', 'Science (Mathematics)', 'Science (Engineering)' ],
        source: "Adapted from Delta Green",
        archetypicalClothing: "button-up shirt, slacks, utilitarian jacket, wireframe glasses, laptop bag",
    },
    {
        name: 'Federal Agent',
        description: 'You are a federal law enforcement officer, possessing the skills and stability to confront crime and conspiracy.',
        group: 'Investigative',
        skillPoints: 'EDU × 2 + DEX × 2',
        creditRatingRange: { min: 30, max: 60 },
        occupationalSkills: ['Accounting', 'Criminology', 'Disguise', 'Drive Auto', 'Firearms (Handgun)', 'Law', 'Persuade', 'Psychology', 'Spot Hidden'],
        source: "Adapted from Delta Green",
        archetypicalClothing: "plain suit and tie under an overcoat, practical shoes, badge wallet",
    },
    {
        name: 'Physician',
        description: 'You are often the first to uncover signs of strange incursions, investigating their disastrous effects on humanity.',
        group: 'Professional',
        skillPoints: 'EDU × 4',
        creditRatingRange: { min: 50, max: 80 },
        occupationalSkills: ['Biology', 'First Aid', 'Latin', 'Medicine', 'Pharmacy', 'Psychology', 'Science (Biology)', 'Science (Chemistry)'],
        source: "Adapted from Delta Green",
        archetypicalClothing: "conservative suit or clinic attire, doctor's bag, clean overcoat",
    },
    {
        name: 'Scientist',
        description: 'You expand human knowledge in a specific field, understanding that some hypotheses should not be tested.',
        group: 'Academic',
        skillPoints: 'EDU × 4',
        creditRatingRange: { min: 30, max: 70 },
        occupationalSkills: ['Astronomy', 'Biology', 'Botany', 'Chemistry', 'Geology', 'Library Use', 'Physics', 'Zoology'],
        source: "Adapted from Delta Green",
        archetypicalClothing: "lab coat over shirtsleeves or practical academic wear, fountain pen, notebook",
    },
    {
        name: 'Special Operator',
        description: 'Part of an elite military force, you have undergone grueling training to serve on the most dangerous missions.',
        group: 'Manual Labor',
        skillPoints: 'EDU × 2 + (DEX × 2 or STR × 2)',
        creditRatingRange: { min: 20, max: 60 },
        occupationalSkills: ['Climb', 'Dodge', 'Fighting (Brawl)', 'Firearms (Rifle/Shotgun)', 'First Aid', 'Stealth', 'Survival', 'Swim'],
        source: "Adapted from Delta Green",
        archetypicalClothing: "plain workwear or field fatigues beneath a civilian coat, sturdy boots, subdued watch",
    },
     {
        name: 'Criminal',
        description: 'A hardened militant or a traditional "black collar" criminal: burglar, extortionist, or thug.',
        group: 'Criminal',
        skillPoints: 'EDU × 2 + DEX × 2',
        creditRatingRange: { min: 5, max: 40 },
        occupationalSkills: ['Appraise', 'Disguise', 'Fighting (Brawl)', 'Firearms (Handgun)', 'Intimidate', 'Locksmith', 'Sleight of Hand', 'Stealth'],
        source: "Adapted from Delta Green",
        archetypicalClothing: "street clothes, leather jacket, gloves, cap pulled low",
    },
    {
        name: 'Firefighter',
        description: 'Your job oscillates between tedium, exhilaration, and investigating scenes after the smoke has cleared.',
        group: 'Manual Labor',
        skillPoints: 'EDU × 2 + (STR × 2 or DEX × 2)',
        creditRatingRange: { min: 20, max: 40 },
        occupationalSkills: ['Climb', 'Drive Auto', 'Electrical Repair', 'Fighting (Brawl)', 'First Aid', 'Mechanical Repair', 'Spot Hidden', 'Throw'],
        source: "Adapted from Delta Green",
        archetypicalClothing: "work jacket, heavy boots, duty pants off-shift; soot-marked gear on occasion",
    },
    {
        name: 'Foreign Service Officer',
        description: 'You travel to strange lands, meet interesting people, and try to get along with them, learning exotic and deadly things.',
        group: 'Professional',
        skillPoints: 'EDU × 4',
        creditRatingRange: { min: 30, max: 70 },
        occupationalSkills: ['Accounting', 'Charm', 'Deception', 'History', 'Law', 'Library Use', 'Other Language', 'Persuade'],
        source: "Adapted from Delta Green",
        archetypicalClothing: "tailored suit, trenchcoat, passport wallet, polished shoes",
    },
    {
        name: 'Intelligence Analyst',
        description: 'You piece together disparate information to find meaning, a dangerous endeavor in this world.',
        group: 'Investigative',
        skillPoints: 'EDU × 4',
        creditRatingRange: { min: 30, max: 60 },
        occupationalSkills: ['Computer Use', 'Criminology', 'History', 'Library Use', 'Other Language', 'Psychology', 'Spot Hidden'],
        source: "Adapted from Delta Green",
        archetypicalClothing: "conservative officewear, cardigan or blazer, wireframe glasses, notebook",
    },
    {
        name: 'Intelligence Case Officer',
        description: 'You recruit people to spy, viewing everyone as a potential threat, liar, or tool to further your agenda.',
        group: 'Investigative',
        skillPoints: 'EDU × 2 + APP × 2',
        creditRatingRange: { min: 30, max: 70 },
        occupationalSkills: ['Charm', 'Deception', 'Disguise', 'Intimidate', 'Law', 'Other Language', 'Persuade', 'Psychology'],
        source: "Adapted from Delta Green",
        archetypicalClothing: "nondescript civilian wear, overcoat and scarf, discreet wristwatch",
    },
    {
        name: 'Lawyer or Business Executive',
        description: 'Your tools are a computer and smartphone. You might be moving millions of dollars, or bits of data, or both.',
        group: 'Professional',
        skillPoints: 'EDU × 4',
        creditRatingRange: { min: 40, max: 85 },
        occupationalSkills: ['Accounting', 'Bargain', 'Intimidate', 'Law', 'Library Use', 'Persuade', 'Psychology'],
        source: "Adapted from Delta Green",
        archetypicalClothing: "well-tailored suit, briefcase, polished shoes, muted tie",
    },
    {
        name: 'Media Specialist',
        description: 'You might be an author, a blogger, a TV reporter, or a scholar of rare texts. You\'ve uncovered the story of a lifetime.',
        group: 'Entertainer',
        skillPoints: 'EDU × 4',
        creditRatingRange: { min: 20, max: 60 },
        occupationalSkills: ['Art (Writing)', 'Charm', 'History', 'Library Use', 'Persuade', 'Psychology', 'Spot Hidden'],
        source: "Adapted from Delta Green",
        archetypicalClothing: "press-ready jacket, messenger bag, camera or notebooks, scuffed shoes",
    },
    {
        name: 'Nurse or Paramedic',
        description: 'Medical professionals are on the front line when awful things happen. That\'s what brought you to this work.',
        group: 'Professional',
        skillPoints: 'EDU × 4',
        creditRatingRange: { min: 20, max: 50 },
        occupationalSkills: ['Drive Auto', 'First Aid', 'Medicine', 'Persuade', 'Psychology', 'Science (Biology)', 'Spot Hidden'],
        source: "Adapted from Delta Green",
        archetypicalClothing: "scrubs under a coat or practical street clothes, comfortable shoes, medical satchel",
    },
    {
        name: 'Pilot or Sailor',
        description: 'Air or sea, commercial or military, your duty is to keep your passengers alive and craft intact.',
        group: 'Manual Labor',
        skillPoints: 'EDU × 2 + DEX × 2',
        creditRatingRange: { min: 30, max: 70 },
        occupationalSkills: ['Electrical Repair', 'Mechanical Repair', 'Navigate', 'Operate Heavy Machinery', 'Pilot (Aircraft)', 'Pilot (Boat)', 'Science (Astronomy)'],
        source: "Adapted from Delta Green",
        archetypicalClothing: "peacoat or bomber jacket, cap, duffel bag, calloused hands",
    },
    {
        name: 'Police Officer',
        description: 'You serve and protect. You walk the beat, answer to an elected law enforcer, or put the pieces together as a detective.',
        group: 'Investigative',
        skillPoints: 'EDU × 2 + (STR × 2 or DEX × 2)',
        creditRatingRange: { min: 20, max: 50 },
        occupationalSkills: ['Criminology', 'Drive Auto', 'Fighting (Brawl)', 'Firearms (Handgun)', 'First Aid', 'Law', 'Persuade', 'Psychology'],
        source: "Adapted from Delta Green",
        archetypicalClothing: "plainclothes detective wear: shirt, tie, overcoat; badge wallet; sturdy shoes",
    },
    {
        name: 'Program Manager',
        description: 'You run an organization. Someone has to secure funding, move resources, and make connections, and that\'s you.',
        group: 'Professional',
        skillPoints: 'EDU × 4',
        creditRatingRange: { min: 40, max: 80 },
        occupationalSkills: ['Accounting', 'Computer Use', 'Intimidate', 'Law', 'Library Use', 'Persuade', 'Psychology'],
        source: "Adapted from Delta Green",
        archetypicalClothing: "business casual with a blazer, lanyard, notebook planner, sensible shoes",
    },
    {
        name: 'Soldier or Marine',
        description: 'When war begins, civilization gets out of the way. With the social contract void, unnatural things creep in at the edges.',
        group: 'Manual Labor',
        skillPoints: 'EDU × 2 + DEX × 2',
        creditRatingRange: { min: 10, max: 40 },
        occupationalSkills: ['Dodge', 'Fighting (Brawl)', 'Firearms (Rifle/Shotgun)', 'First Aid', 'Mechanical Repair', 'Stealth', 'Survival'],
        source: "Adapted from Delta Green",
        archetypicalClothing: "surplus field jacket, sturdy boots, short haircut, worn duffel",
    }
];
