import type { DGItem } from '../../types';
import { normalizeItemName } from '../../utils';

const regencyItem = (section: string, name: string, price: string, description: string): DGItem => ({
  section,
  name: normalizeItemName(name),
  description,
  price,
  sourceType: 'core',
  sourceName: 'Regency Cthulhu',
  sourcePage: null,
});

export const ITEMS_FROM_PRICES: DGItem[] = [
  regencyItem('Food & Drink', 'Bread (4lb loaf)', '13d', 'A standard country or town loaf for daily meals.'),
  regencyItem('Food & Drink', 'Butter (per pound)', '12d', 'A pound of butter for table use or cooking.'),
  regencyItem('Food & Drink', 'Cheese (per pound)', '9d', 'A common hard cheese, purchased by the pound.'),
  regencyItem('Food & Drink', 'Meat (per pound)', '7d', 'A typical butchered cut, priced for ordinary domestic use.'),
  regencyItem('Food & Drink', 'Sugar (per pound)', '8d', 'Refined sugar for the table and pantry.'),
  regencyItem('Food & Drink', 'Tea (per pound)', '8s', 'Tea imported for the household and tea table.'),
  regencyItem('Food & Drink', 'Coffee (per pound)', '6s', 'Coffee for breakfast, calls, and private refreshment.'),
  regencyItem('Food & Drink', 'Table Wine (bottle)', '2s/6d', 'An ordinary bottle of table wine for domestic or social use.'),
  regencyItem('Food & Drink', 'Ale (pint)', '1d', 'A common pint of ale from a tavern or inn.'),

  regencyItem('Clothing & Accessories', 'Simple White Dress', '5s', 'A plain dress suitable for informal daytime wear.'),
  regencyItem('Clothing & Accessories', 'Velveteen (per yard)', '2s/10d', 'Velveteen fabric sold by the yard for sturdy clothing.'),
  regencyItem('Clothing & Accessories', 'White Silk Handkerchief', '6s', 'A neat silk handkerchief for display or travel.'),
  regencyItem('Clothing & Accessories', 'Women\'s Gloves (Fabric)', '4s', 'Fabric gloves for routine social wear.'),
  regencyItem('Clothing & Accessories', 'Women\'s Shoes (Fabric)', '9s', 'Fabric shoes for indoor or light outdoor use.'),
  regencyItem('Clothing & Accessories', 'Women\'s Walking Boots', '£2', 'Sturdy walking boots for town or country travel.'),
  regencyItem('Clothing & Accessories', 'Cambric Muslin (per yard)', '4s/6d', 'Fine cambric muslin for dresses and trims.'),
  regencyItem('Clothing & Accessories', 'Cotton Fabric (Plain, per yard)', '1s', 'Plain cotton for simple garments and underthings.'),
  regencyItem('Clothing & Accessories', 'Dress Length of Silk', '26s', 'A length of silk suitable for a fashionable dress.'),
  regencyItem('Clothing & Accessories', 'Fan', '5s', 'A painted or folded fan for the drawing room and ballroom.'),
  regencyItem('Clothing & Accessories', 'Ribbons (per yard)', '2d', 'Ribbon trim sold by the yard.'),
  regencyItem('Clothing & Accessories', 'Silk Purse', '2s', 'A small silk purse for coins or calling tokens.'),
  regencyItem('Clothing & Accessories', 'Silk Stockings (Pair)', '2s', 'A pair of fine silk stockings.'),
  regencyItem('Clothing & Accessories', 'Men\'s Gloves (Leather)', '10s/6d', 'Well-made leather gloves for riding or formal wear.'),
  regencyItem('Clothing & Accessories', 'Men\'s Shoes (Leather)', '10s/6d', 'Good leather shoes for town or travel.'),
  regencyItem('Clothing & Accessories', 'Tailcoat', '£3', 'A formal tailcoat fit for evening calls and balls.'),
  regencyItem('Clothing & Accessories', 'Morning Coat', '£2/10s', 'A respectable daytime coat for business and visits.'),
  regencyItem('Clothing & Accessories', 'Top Hat', '£1/1s', 'A tall hat for smart public appearances.'),
  regencyItem('Clothing & Accessories', 'Cravat', '5s', 'A neckcloth worn by gentlemen of taste.'),
  regencyItem('Clothing & Accessories', 'Walking Cane', '10s', 'A cane for carriage, leisure, and occasional self-defense.'),
  regencyItem('Clothing & Accessories', 'Riding Boots', '£2', 'Boots made for horse riding and stable life.'),
  regencyItem('Clothing & Accessories', 'Riding Habit', '£3', 'A tailored riding outfit for a lady on horseback.'),
  regencyItem('Clothing & Accessories', 'Riding Hat', '15s', 'A practical hat worn for riding and country travel.'),
  regencyItem('Clothing & Accessories', 'Riding Crop', '5s', 'A short crop used while riding or handling horses.'),
  regencyItem('Clothing & Accessories', 'Gloves, Riding', '5s', 'Gloves designed for horseback travel and stable work.'),
  regencyItem('Clothing & Accessories', 'Pelisse', '£2', 'A warm outer garment worn over a dress for travel.'),
  regencyItem('Clothing & Accessories', 'Bonnet', '£1', 'A fashionable bonnet for public outings.'),
  regencyItem('Clothing & Accessories', 'Parasol', '10s', 'A light umbrella for sun and rain alike.'),
  regencyItem('Clothing & Accessories', 'Reticule', '5s', 'A small handbag carried by fashionable ladies.'),
  regencyItem('Clothing & Accessories', 'Shawl', '15s', 'A light wrap for travel or evening cool.'),
  regencyItem('Clothing & Accessories', 'Sewing Kit', '5s', 'Needles, thread, scissors, and other small repairs.'),
  regencyItem('Clothing & Accessories', 'Hairpins', '1s', 'Pins and small fastenings for arranging hair.'),
  regencyItem('Clothing & Accessories', 'Snuff Box', '10s', 'A small decorative box for snuff or private keepsakes.'),
  regencyItem('Clothing & Accessories', 'Pocket Watch', '£1', 'A practical watch kept in a waistcoat pocket.'),
  regencyItem('Clothing & Accessories', 'Calling Cards', '5s', 'Printed visiting cards used for formal calls.'),
  regencyItem('Clothing & Accessories', 'Travel Cloak', '£3', 'A weatherproof cloak for coach journeys and roadside weather.'),

  regencyItem('Travel & Transport', 'Horse and Saddle', '£25', 'A reliable saddle horse with the tack needed for travel.'),
  regencyItem('Travel & Transport', 'Pair of Carriage Horses', '50 guineas', 'A matched pair of carriage horses for travel and display.'),
  regencyItem('Travel & Transport', 'Carriage', '45 guineas', 'A private carriage of modest to fine quality.'),
  regencyItem('Travel & Transport', 'Phaeton', '60 guineas', 'A fashionable open carriage for swift travel.'),
  regencyItem('Travel & Transport', 'Curricle', '45 guineas', 'A sporty two-wheeled carriage favored by men of fashion.'),
  regencyItem('Travel & Transport', 'Gig', '35 guineas', 'A light two-wheeled carriage for one or two travelers.'),
  regencyItem('Travel & Transport', 'Barouche', '85 guineas', 'A larger open carriage for social display and comfort.'),
  regencyItem('Travel & Transport', 'Landau', '120 guineas', 'A luxurious carriage that can be open or closed.'),
  regencyItem('Travel & Transport', 'Brougham', '90 guineas', 'A closed carriage suited to discreet town travel.'),
  regencyItem('Travel & Transport', 'Post Chaise', '35 guineas', 'A hired carriage for long-distance travel with fresh horses.'),
  regencyItem('Travel & Transport', 'Hansom Cab', '20 guineas', 'A hired two-wheeled cab for urban travel.'),
  regencyItem('Travel & Transport', 'Carriage Lanterns & Tack', '£8', 'Lanterns, harness, tack, and other coach accessories.'),
  regencyItem('Travel & Transport', 'Compass', '5s', 'A pocket compass for road or field navigation.'),
  regencyItem('Travel & Transport', 'Field Glasses', '£6', 'A pair of quality field glasses for observation.'),
  regencyItem('Travel & Transport', 'Lantern', '10s', 'A portable lantern for night roads and dark rooms.'),
  regencyItem('Travel & Transport', 'Map Case', '10s', 'A leather case for folded maps and travel papers.'),
  regencyItem('Travel & Transport', 'Notebook', '2s', 'A small notebook for travel notes and observations.'),
  regencyItem('Travel & Transport', 'Pen and Ink Set', '1s', 'A portable set for correspondence and notes.'),
  regencyItem('Travel & Transport', 'First Aid Kit', '5s', 'A compact kit of bandages and basic supplies.'),
  regencyItem('Travel & Transport', 'Rope (50 feet)', '2s', 'A length of useful rope for travel, rescue, or climbing.'),

  regencyItem('Printed Matter & Leisure', 'Book (Minerva Press)', '6s', 'A popular printed novel or pamphlet.'),
  regencyItem('Printed Matter & Leisure', 'Encyclopedia (One Volume)', '£3/13s/6d', 'A substantial reference volume for the educated household.'),
  regencyItem('Printed Matter & Leisure', 'Piano', '30 guineas', 'A parlor piano for homes with money and room enough.'),
  regencyItem('Printed Matter & Leisure', 'Writing Desk Set', '£2', 'Ink, quills or pens, sealing wax, and stationery for letters.'),
  regencyItem('Printed Matter & Leisure', 'Tea Service', '£2', 'A respectable tea service for entertaining guests.'),
  regencyItem('Printed Matter & Leisure', 'Toothbrush', '3d', 'A personal toothbrush for daily care.'),
  regencyItem('Printed Matter & Leisure', 'Matches', '1d', 'A small packet of matches.'),
  regencyItem('Printed Matter & Leisure', 'Candles (per week)', '1s/2d', 'A household allowance of candles for a week.'),
  regencyItem('Printed Matter & Leisure', 'Coal (per annum)', '£50', 'A yearly coal allowance for heating and cooking.'),
  regencyItem('Printed Matter & Leisure', 'Opera Glasses', '£1/1s', 'A pair of small glasses for the theater or ballroom.'),

  regencyItem('Household & Services', 'House Rent (London, medium-sized house)', '£12-£25', 'A respectable London house rented per annum.'),
  regencyItem('Household & Services', 'Female Servant (per annum, rent and board included)', '£5-£15', 'Annual wages for a female servant, often with board.'),
  regencyItem('Household & Services', 'Male Servant (per annum, rent and board included)', '£20-£60', 'Annual wages for a male servant, often with board.'),
];
