import type { Occupation } from '../../types';

const gentryWeaponChoices = [
  'Fighting (Brawl)',
  'Fighting (Axe)',
  'Fighting (Flail)',
  'Fighting (Garrote)',
  'Fighting (Spear)',
  'Fighting (Rapier)',
  'Fighting (Saber)',
  'Fighting (Whip)',
  'Firearms (Pistol)',
  'Firearms (Rifle/Blunderbuss)',
];

const regencyArtChoices = [
  'Art and Craft (Acting)',
  'Art and Craft (Art Appreciation)',
  'Art and Craft (Embroidery)',
  'Art and Craft (Fine Art)',
  'Art and Craft (Forgery)',
  'Art and Craft (Piano)',
  'Art and Craft (Violin)',
  'Art and Craft (Singing)',
  'Art and Craft (Poetry)',
  'Art and Craft (Sculpture)',
];

const regencyCraftChoices = [
  'Art and Craft (Blacksmithing)',
  'Art and Craft (Carpentry)',
  'Art and Craft (Cooking)',
  'Art and Craft (Pottery)',
  'Art and Craft (Sewing)',
];

const regencyLanguageChoices = [
  'Language (French)',
  'Language (German)',
  'Language (Italian)',
  'Language (Latin)',
  'Language (Greek)',
  'Language (Spanish)',
  'Language (Arabic)',
];

const anySkill = [{ count: 1, options: ['*'] }];

export const OCCUPATIONS: Occupation[] = [
  {
    name: 'Actor',
    description: 'A stage performer, celebrated or struggling, who moves easily through drawing rooms, theaters, and gossip.',
    group: 'Entertainer',
    skillPoints: 'EDU × 2 + APP × 2',
    creditRatingRange: { min: 20, max: 60 },
    occupationalSkills: ['Art and Craft (Acting)', 'Charm', 'Fast Talk', 'Persuade', 'Psychology', 'Spot Hidden'],
    choiceGroups: [
      { count: 1, options: regencyArtChoices },
      ...anySkill,
    ],
    source: 'Regency Cthulhu',
  },
  {
    name: 'Accountant',
    description: 'A careful steward of ledgers, rents, and accounts for estates, firms, and wealthy households.',
    group: 'Professional',
    skillPoints: 'EDU × 4',
    creditRatingRange: { min: 30, max: 70 },
    occupationalSkills: ['Accounting', 'Appraise', 'Library Use', 'Persuade', 'Spot Hidden'],
    choiceGroups: anySkill,
    source: 'Regency Cthulhu',
  },
  {
    name: 'Antiquarian',
    description: 'A collector, dealer, or amateur scholar of old books, relics, and curiosities.',
    group: 'Academic',
    skillPoints: 'EDU × 4',
    creditRatingRange: { min: 30, max: 70 },
    occupationalSkills: ['Appraise', 'History', 'Library Use', 'Language (Other)', 'Spot Hidden'],
    choiceGroups: [
      { count: 1, options: regencyArtChoices },
      { count: 1, options: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'] },
      ...anySkill,
    ],
    source: 'Regency Cthulhu',
  },
  {
    name: 'Antique Dealer',
    description: 'A seller of old furniture, art, and curios who knows how to flatter wealthy clients and spot a fake.',
    group: 'Investigative',
    skillPoints: 'EDU × 2 + APP × 2',
    creditRatingRange: { min: 20, max: 60 },
    occupationalSkills: ['Appraise', 'History', 'Library Use', 'Language (Other)', 'Persuade', 'Spot Hidden'],
    choiceGroups: anySkill,
    source: 'Regency Cthulhu',
  },
  {
    name: 'Archaeologist',
    description: 'A field scholar who digs through ruins, monuments, and collections in search of the ancient past.',
    group: 'Academic',
    skillPoints: 'EDU × 4',
    creditRatingRange: { min: 30, max: 70 },
    occupationalSkills: ['Archaeology', 'History', 'Library Use', 'Language (Other)', 'Navigate', 'Spot Hidden'],
    choiceGroups: anySkill,
    source: 'Regency Cthulhu',
  },
  {
    name: 'Architect',
    description: 'A designer of homes, estates, and civic buildings, often moving between patrons, sites, and drafts.',
    group: 'Professional',
    skillPoints: 'EDU × 4',
    creditRatingRange: { min: 30, max: 70 },
    occupationalSkills: ['Accounting', 'Appraise', 'Library Use', 'Persuade', 'Spot Hidden'],
    choiceGroups: [
      { count: 1, options: regencyCraftChoices },
      ...anySkill,
    ],
    source: 'Regency Cthulhu',
  },
  {
    name: 'Artist',
    description: 'A painter, sculptor, or other creative figure whose work depends on patronage and reputation.',
    group: 'Entertainer',
    skillPoints: 'EDU × 2 + POW × 2 or INT × 2',
    creditRatingRange: { min: 20, max: 60 },
    occupationalSkills: ['History', 'Language (Other)', 'Library Use', 'Persuade', 'Psychology', 'Spot Hidden'],
    choiceGroups: [
      { count: 2, options: regencyArtChoices },
      ...anySkill,
    ],
    source: 'Regency Cthulhu',
  },
  {
    name: 'Author',
    description: 'A writer of novels, poems, essays, or plays, often living by wit, observation, and patronage.',
    group: 'Academic',
    skillPoints: 'EDU × 4',
    creditRatingRange: { min: 10, max: 50 },
    occupationalSkills: ['Art and Craft (Poetry)', 'History', 'Library Use', 'Language (Other)', 'Language (Own)', 'Psychology'],
    choiceGroups: [
      { count: 1, options: ['Natural World', 'Occult', 'Religion'] },
      ...anySkill,
    ],
    source: 'Regency Cthulhu',
  },
  {
    name: 'Boxer',
    description: 'A prize-fighter or amateur pugilist whose reputation rests on fists, stamina, and nerve.',
    group: 'Entertainer',
    skillPoints: 'EDU × 2 + STR × 2 or DEX × 2',
    creditRatingRange: { min: 10, max: 40 },
    occupationalSkills: ['Dodge', 'Fighting (Brawl)', 'Intimidate', 'Jump', 'Psychology', 'Spot Hidden'],
    choiceGroups: [
      { count: 1, options: ['*'] },
    ],
    source: 'Regency Cthulhu',
  },
  {
    name: 'Book Dealer',
    description: 'A seller of books, pamphlets, and printed curiosities who works among collectors and scholars.',
    group: 'Academic',
    skillPoints: 'EDU × 2 + APP × 2',
    creditRatingRange: { min: 20, max: 60 },
    occupationalSkills: ['Appraise', 'History', 'Library Use', 'Language (Other)', 'Persuade', 'Spot Hidden'],
    choiceGroups: anySkill,
    source: 'Regency Cthulhu',
  },
  {
    name: 'Burglar',
    description: 'A thief who enters houses, rooms, or coaches by stealth and opportunity.',
    group: 'Criminal',
    skillPoints: 'EDU × 2 + DEX × 2 or INT × 2',
    creditRatingRange: { min: 0, max: 20 },
    occupationalSkills: ['Climb', 'Disguise', 'Fighting (Brawl)', 'Listen', 'Sleight of Hand', 'Stealth', 'Spot Hidden'],
    choiceGroups: anySkill,
    source: 'Regency Cthulhu',
  },
  {
    name: 'Butler/Valet/Maid',
    description: "The highest-ranking servants of a household, entrusted with order, access, and the family's private affairs.",
    group: 'Manual Labor',
    skillPoints: 'INT × 2 + POW × 2',
    creditRatingRange: { min: 10, max: 40 },
    occupationalSkills: ['Dancing', 'Etiquette', 'Fast Talk', 'Listen', 'Persuade', 'Spot Hidden'],
    choiceGroups: [
      { count: 1, options: regencyArtChoices },
      { count: 1, options: regencyLanguageChoices },
      ...anySkill,
    ],
    special: 'Butlers, valets, and maids are the highest-ranking household servants. Their Credit Rating may be capped higher by Keeper discretion.',
    source: 'Regency Cthulhu',
  },
  {
    name: 'Clergy (Member of the)',
    description: 'A minister or cleric, educated in doctrine and social influence, moving between parishes and patrons.',
    group: 'Professional',
    skillPoints: 'EDU × 4',
    creditRatingRange: { min: 20, max: 70 },
    occupationalSkills: ['History', 'Language (Latin)', 'Library Use', 'Persuade', 'Psychology', 'Religion'],
    choiceGroups: [
      { count: 1, options: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'] },
      ...anySkill,
    ],
    source: 'Regency Cthulhu',
  },
  {
    name: 'Craftsperson',
    description: 'A skilled maker or repairer of goods, from carpenters and coopers to dressmakers and jewelers.',
    group: 'Manual Labor',
    skillPoints: 'EDU × 2 + DEX × 2 or STR × 2',
    creditRatingRange: { min: 10, max: 50 },
    occupationalSkills: ['Accounting', 'Appraise', 'Mechanical Repair', 'Natural World', 'Spot Hidden'],
    choiceGroups: [
      { count: 1, options: regencyCraftChoices },
      { count: 1, options: ['Charm', 'Persuade'] },
      ...anySkill,
    ],
    source: 'Regency Cthulhu',
  },
  {
    name: 'Criminal',
    description: 'A general underworld figure who survives by deception, violence, or illicit trade.',
    group: 'Criminal',
    skillPoints: 'EDU × 2 + DEX × 2 or STR × 2',
    creditRatingRange: { min: 0, max: 30 },
    occupationalSkills: ['Disguise', 'Fighting (Brawl)', 'Fast Talk', 'Listen', 'Sleight of Hand', 'Stealth', 'Spot Hidden'],
    choiceGroups: [
      { count: 1, options: ['Appraise', 'Locksmith', 'Persuade', 'Psychology'] },
      ...anySkill,
    ],
    source: 'Regency Cthulhu',
  },
  {
    name: 'Doctor',
    description: 'A physician or surgeon with practical medical knowledge and access to the homes of the wealthy.',
    group: 'Professional',
    skillPoints: 'EDU × 4',
    creditRatingRange: { min: 30, max: 80 },
    occupationalSkills: ['First Aid', 'Language (Latin)', 'Library Use', 'Medicine', 'Persuade', 'Psychology'],
    choiceGroups: [
      { count: 1, options: ['Natural Philosophy', 'Religion', 'Language (Other)'] },
      ...anySkill,
    ],
    source: 'Regency Cthulhu',
  },
  {
    name: 'Driver (Carriage)',
    description: 'A coachman, cab driver, or carriage hand who knows roads, horses, and passengers alike.',
    group: 'Manual Labor',
    skillPoints: 'EDU × 2 + DEX × 2 or STR × 2',
    creditRatingRange: { min: 10, max: 30 },
    occupationalSkills: ['Animal Handling', 'Drive Carriage/Cart', 'Listen', 'Navigate', 'Persuade', 'Spot Hidden', 'Track'],
    choiceGroups: [
      { count: 1, options: ['Fighting (Brawl)', 'Fighting (Whip)'] },
      ...anySkill,
    ],
    source: 'Regency Cthulhu',
  },
  {
    name: 'Entertainer',
    description: 'A performer of music, story, or spectacle who makes a living from public attention.',
    group: 'Entertainer',
    skillPoints: 'EDU × 2 + APP × 2',
    creditRatingRange: { min: 10, max: 60 },
    occupationalSkills: ['Art and Craft (Acting)', 'Charm', 'Fast Talk', 'Persuade', 'Psychology', 'Spot Hidden'],
    choiceGroups: [
      { count: 1, options: regencyArtChoices },
      ...anySkill,
    ],
    source: 'Regency Cthulhu',
  },
  {
    name: 'Explorer',
    description: 'A traveler and investigator who ventures beyond familiar roads in search of new places and knowledge.',
    group: 'Professional',
    skillPoints: 'EDU × 2 + INT × 2',
    creditRatingRange: { min: 20, max: 70 },
    occupationalSkills: ['Climb', 'History', 'Language (Other)', 'Navigate', 'Spot Hidden', 'Survival'],
    choiceGroups: [
      { count: 1, options: ['Natural Philosophy', 'Anthropology', 'Archaeology'] },
      ...anySkill,
    ],
    source: 'Regency Cthulhu',
  },
  {
    name: 'Farmer',
    description: 'A land worker or tenant who lives close to animals, weather, and practical labor.',
    group: 'Manual Labor',
    skillPoints: 'EDU × 2 + STR × 2 or DEX × 2',
    creditRatingRange: { min: 10, max: 30 },
    occupationalSkills: ['Animal Handling', 'Drive Carriage/Cart', 'Natural World', 'Spot Hidden', 'Stealth', 'Track'],
    choiceGroups: [
      { count: 1, options: ['Art and Craft (Cooking)', 'Art and Craft (Sewing)', 'Mechanical Repair'] },
      ...anySkill,
    ],
    source: 'Regency Cthulhu',
  },
  {
    name: 'Gambler',
    description: 'A card player and risk-taker who lives by nerve, bluff, and reading the table.',
    group: 'Entertainer',
    skillPoints: 'EDU × 2 + APP × 2',
    creditRatingRange: { min: 10, max: 50 },
    occupationalSkills: ['Fast Talk', 'Gaming', 'Persuade', 'Psychology', 'Sleight of Hand', 'Spot Hidden'],
    choiceGroups: anySkill,
    source: 'Regency Cthulhu',
  },
  {
    name: 'Gentleman',
    description: 'A member of the landed gentry who lives by wealth, privilege, and social ease.',
    group: 'Upper Class',
    skillPoints: '(EDU × 2) + (APP × 2)',
    creditRatingRange: { min: 50, max: 90 },
    occupationalSkills: ['Charm', 'Dancing', 'Etiquette', 'Fashion', 'Gaming', 'Ride'],
    choiceGroups: [
      { count: 1, options: gentryWeaponChoices },
      ...anySkill,
    ],
    special: 'Gentlemen are expected to add one additional personal hobby skill beyond their social and combat expertise.',
    source: 'Regency Cthulhu',
  },
  {
    name: 'Gentlewoman',
    description: 'A daughter of the gentry whose social position shapes her education, expectations, and opportunities.',
    group: 'Upper Class',
    skillPoints: '(EDU × 2) + (APP × 2)',
    creditRatingRange: { min: 50, max: 90 },
    occupationalSkills: ['Dancing', 'Etiquette', 'Fashion', 'Persuade', 'Ride'],
    choiceGroups: [
      { count: 2, options: regencyArtChoices },
      { count: 1, options: regencyLanguageChoices },
      { count: 1, options: gentryWeaponChoices },
      ...anySkill,
    ],
    special: 'Gentlewomen often pursue art, music, languages, and refined accomplishments as a matter of status.',
    source: 'Regency Cthulhu',
  },
  {
    name: 'Journalist',
    description: 'A reporter, pamphleteer, or chronicler who gathers stories from drawing rooms and the streets alike.',
    group: 'Investigative',
    skillPoints: 'EDU × 4',
    creditRatingRange: { min: 20, max: 50 },
    occupationalSkills: ['History', 'Library Use', 'Language (Own)', 'Persuade', 'Psychology', 'Spot Hidden'],
    choiceGroups: [
      { count: 1, options: ['Art and Craft (Writing)', 'Art and Craft (Poetry)'] },
      ...anySkill,
    ],
    source: 'Regency Cthulhu',
  },
  {
    name: 'Lawyer',
    description: 'An advocate and counselor who knows how to maneuver through precedent, contracts, and courtrooms.',
    group: 'Professional',
    skillPoints: 'EDU × 4',
    creditRatingRange: { min: 30, max: 80 },
    occupationalSkills: ['Accounting', 'History', 'Library Use', 'Language (Latin)', 'Persuade', 'Psychology'],
    choiceGroups: anySkill,
    source: 'Regency Cthulhu',
  },
  {
    name: 'Librarian',
    description: 'A guardian of books and records, responsible for finding the right reference in the right moment.',
    group: 'Academic',
    skillPoints: 'EDU × 4',
    creditRatingRange: { min: 20, max: 50 },
    occupationalSkills: ['Accounting', 'Library Use', 'Language (Other)', 'Language (Own)', 'Persuade'],
    choiceGroups: anySkill,
    source: 'Regency Cthulhu',
  },
  {
    name: 'Military Officer',
    description: 'A professional officer or younger son of the gentry, trained to command men and manage campaigns.',
    group: 'Professional',
    skillPoints: 'EDU × 2 + DEX × 2 or STR × 2',
    creditRatingRange: { min: 20, max: 70 },
    occupationalSkills: ['Accounting', 'Firearms (Pistol)', 'Navigate', 'Persuade', 'Psychology', 'Ride'],
    choiceGroups: [
      { count: 1, options: ['Artillery', 'Fighting (Brawl)', 'Fighting (Rapier)', 'Fighting (Saber)'] },
      { count: 1, options: ['Fighting (Axe)', 'Fighting (Spear)', 'Fighting (Whip)'] },
      ...anySkill,
    ],
    source: 'Regency Cthulhu',
  },
  {
    name: 'Missionary',
    description: 'A traveling religious worker who carries faith, aid, and moral confidence into distant places.',
    group: 'Professional',
    skillPoints: 'EDU × 4',
    creditRatingRange: { min: 10, max: 40 },
    occupationalSkills: ['First Aid', 'Language (Other)', 'Mechanical Repair', 'Natural World', 'Persuade', 'Religion'],
    choiceGroups: [
      { count: 1, options: regencyLanguageChoices },
      ...anySkill,
    ],
    source: 'Regency Cthulhu',
  },
  {
    name: 'Miner',
    description: 'A laborer used to hard work underground, dangerous conditions, and practical teamwork.',
    group: 'Manual Labor',
    skillPoints: 'EDU × 2 + STR × 2',
    creditRatingRange: { min: 10, max: 30 },
    occupationalSkills: ['Climb', 'Demolitions', 'Listen', 'Mechanical Repair', 'Spot Hidden', 'Stealth', 'Track'],
    choiceGroups: anySkill,
    source: 'Regency Cthulhu',
  },
  {
    name: 'Museum Curator',
    description: 'A steward of collections who manages displays, acquisitions, patrons, and the order of displayed history.',
    group: 'Academic',
    skillPoints: 'EDU × 4',
    creditRatingRange: { min: 30, max: 70 },
    occupationalSkills: ['Appraise', 'History', 'Library Use', 'Language (Other)', 'Persuade', 'Spot Hidden'],
    choiceGroups: [
      { count: 1, options: regencyArtChoices },
      ...anySkill,
    ],
    source: 'Regency Cthulhu',
  },
  {
    name: 'Musician',
    description: 'A performer whose livelihood depends on taste, timing, and the favor of the rooms they play in.',
    group: 'Entertainer',
    skillPoints: 'EDU × 2 + DEX × 2 or POW × 2',
    creditRatingRange: { min: 10, max: 50 },
    occupationalSkills: ['Listen', 'Psychology', 'Persuade'],
    choiceGroups: [
      { count: 1, options: ['Art and Craft (Piano)', 'Art and Craft (Violin)', 'Art and Craft (Singing)'] },
      { count: 1, options: ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'] },
      ...anySkill,
    ],
    source: 'Regency Cthulhu',
  },
  {
    name: 'Nouveau Riche',
    description: 'A family whose wealth is new enough to purchase comfort, but not always social acceptance.',
    group: 'Upper Class',
    skillPoints: '(INT × 2) + (POW × 2)',
    creditRatingRange: { min: 50, max: 90 },
    occupationalSkills: ['Accounting', 'Appraise', 'Art and Craft (Business)', 'Dancing', 'Fast Talk', 'Persuade', 'Ride'],
    choiceGroups: [
      { count: 1, options: gentryWeaponChoices },
      ...anySkill,
    ],
    special: 'A Keeper may permit Nouveau Riche investigators to rise into aristocratic circles only with good reason and great expense.',
    source: 'Regency Cthulhu',
  },
  {
    name: 'Occultist',
    description: 'A student of hidden lore, secret societies, and the supernatural ideas fashionable among the curious.',
    group: 'Lovecraftian',
    skillPoints: 'EDU × 4',
    creditRatingRange: { min: 20, max: 60 },
    occupationalSkills: ['History', 'Language (Other)', 'Library Use', 'Occult', 'Persuade', 'Religion'],
    choiceGroups: [
      { count: 1, options: ['Natural Philosophy', 'Lore', 'Mesmerism'] },
      ...anySkill,
    ],
    source: 'Regency Cthulhu',
  },
  {
    name: 'Pharmacist',
    description: 'A dispenser of medicines, tonics, and household remedies who knows chemistry in practical, pre-modern terms.',
    group: 'Professional',
    skillPoints: 'EDU × 4',
    creditRatingRange: { min: 20, max: 60 },
    occupationalSkills: ['Accounting', 'Appraise', 'Library Use', 'Medicine', 'Natural Philosophy', 'Persuade'],
    choiceGroups: anySkill,
    source: 'Regency Cthulhu',
  },
  {
    name: 'Prostitute',
    description: 'A sex worker navigating danger, secrecy, and social power in a society that judges while it consumes.',
    group: 'Criminal',
    skillPoints: 'INT × 2 + APP × 2',
    creditRatingRange: { min: 0, max: 40 },
    occupationalSkills: ['Charm', 'Fast Talk', 'Listen', 'Persuade', 'Psychology', 'Spot Hidden', 'Stealth'],
    choiceGroups: anySkill,
    source: 'Regency Cthulhu',
  },
  {
    name: 'Researcher',
    description: 'A scholar devoted to discovery, cataloguing, and argument in a library, university, or private study.',
    group: 'Academic',
    skillPoints: 'EDU × 4',
    creditRatingRange: { min: 20, max: 70 },
    occupationalSkills: ['History', 'Language (Other)', 'Library Use', 'Natural Philosophy', 'Persuade', 'Spot Hidden'],
    choiceGroups: [
      { count: 1, options: ['Archaeology', 'Anthropology', 'Occult', 'Religion'] },
      ...anySkill,
    ],
    source: 'Regency Cthulhu',
  },
  {
    name: 'Sailor',
    description: 'A seaman who knows ships, ports, weather, and the practical life of travel by water.',
    group: 'Manual Labor',
    skillPoints: 'EDU × 2 + STR × 2 or DEX × 2',
    creditRatingRange: { min: 10, max: 30 },
    occupationalSkills: ['Climb', 'Fighting (Brawl)', 'Listen', 'Navigate', 'Pilot (Boat)', 'Spot Hidden', 'Swim'],
    choiceGroups: [
      { count: 1, options: ['First Aid', 'Rope Use', 'Track'] },
      ...anySkill,
    ],
    source: 'Regency Cthulhu',
  },
  {
    name: 'Servant (Footman)',
    description: 'A male servant whose duties include carrying, waiting, announcing, and looking impeccable in livery.',
    group: 'Manual Labor',
    skillPoints: 'INT × 2 + POW × 2',
    creditRatingRange: { min: 10, max: 30 },
    occupationalSkills: ['Dancing', 'Etiquette', 'Fashion', 'Persuade', 'Ride'],
    choiceGroups: [
      { count: 2, options: regencyArtChoices },
      { count: 1, options: regencyLanguageChoices },
      ...anySkill,
    ],
    special: 'Footmen usually serve upper-class households and are expected to move easily in polite society.',
    source: 'Regency Cthulhu',
  },
  {
    name: 'Servant (Housemaid)',
    description: "A female servant who keeps the household clean, orderly, and ready for the family's daily needs.",
    group: 'Manual Labor',
    skillPoints: 'INT × 2 + POW × 2',
    creditRatingRange: { min: 10, max: 30 },
    occupationalSkills: ['Dodge', 'Etiquette', 'Fashion', 'Fast Talk', 'Listen', 'Spot Hidden', 'Stealth'],
    choiceGroups: [
      { count: 1, options: ['Art and Craft (Cooking)', 'Art and Craft (Sewing)'] },
      ...anySkill,
    ],
    special: 'Housemaids are expected to be efficient, discreet, and always aware of the household hierarchy.',
    source: 'Regency Cthulhu',
  },
  {
    name: 'Shopkeeper',
    description: 'A tradesperson or shop owner who lives by merchandise, customers, and reputation.',
    group: 'Manual Labor',
    skillPoints: 'EDU × 2 + APP × 2',
    creditRatingRange: { min: 20, max: 60 },
    occupationalSkills: ['Accounting', 'Appraise', 'Fast Talk', 'Persuade', 'Spot Hidden'],
    choiceGroups: [
      { count: 1, options: regencyCraftChoices },
      ...anySkill,
    ],
    source: 'Regency Cthulhu',
  },
  {
    name: 'Smuggler',
    description: 'A covert mover of illicit goods along roads, coastline, and through the gaps in social order.',
    group: 'Criminal',
    skillPoints: 'EDU × 2 + DEX × 2 or INT × 2',
    creditRatingRange: { min: 0, max: 30 },
    occupationalSkills: ['Disguise', 'Fast Talk', 'Listen', 'Navigate', 'Sleight of Hand', 'Stealth', 'Track'],
    choiceGroups: anySkill,
    source: 'Regency Cthulhu',
  },
  {
    name: 'Soldier/Marine',
    description: 'An enlisted man or marine trained for discipline, violence, and following orders in dangerous places.',
    group: 'War',
    skillPoints: 'EDU × 2 + STR × 2 or DEX × 2',
    creditRatingRange: { min: 10, max: 40 },
    occupationalSkills: ['Dodge', 'Fighting (Brawl)', 'Firearms (Pistol)', 'Listen', 'Spot Hidden', 'Stealth', 'Survival'],
    choiceGroups: [
      { count: 1, options: ['Artillery', 'Fighting (Axe)', 'Fighting (Spear)', 'Fighting (Rapier)'] },
      ...anySkill,
    ],
    source: 'Regency Cthulhu',
  },
  {
    name: 'Spy',
    description: 'A clandestine observer who survives by secrecy, observation, and the manipulation of information.',
    group: 'Investigative',
    skillPoints: 'EDU × 2 + APP × 2 or INT × 2',
    creditRatingRange: { min: 20, max: 60 },
    occupationalSkills: ['Disguise', 'Fast Talk', 'Listen', 'Persuade', 'Psychology', 'Stealth', 'Spot Hidden'],
    choiceGroups: [
      { count: 1, options: ['Language (French)', 'Language (German)', 'Language (Italian)', 'Language (Latin)', 'Language (Greek)'] },
      { count: 1, options: ['Read Lips', 'Sleight of Hand', 'Locksmith'] },
      ...anySkill,
    ],
    source: 'Regency Cthulhu',
  },
  {
    name: 'Undertaker',
    description: 'A funeral professional who knows the dead, the grieving, and the practical arrangements of death.',
    group: 'Manual Labor',
    skillPoints: 'EDU × 2 + APP × 2',
    creditRatingRange: { min: 20, max: 50 },
    occupationalSkills: ['Appraise', 'Fast Talk', 'Listen', 'Persuade', 'Spot Hidden'],
    choiceGroups: [
      { count: 1, options: regencyCraftChoices },
      ...anySkill,
    ],
    source: 'Regency Cthulhu',
  },
  {
    name: 'Zealot',
    description: 'A fervent believer whose certainty can inspire, terrify, or push them into dangerous extremes.',
    group: 'Lovecraftian',
    skillPoints: 'EDU × 2 + POW × 2',
    creditRatingRange: { min: 0, max: 40 },
    occupationalSkills: ['Fast Talk', 'Intimidate', 'Occult', 'Persuade', 'Psychology', 'Religion'],
    choiceGroups: anySkill,
    source: 'Regency Cthulhu',
  },
  {
    name: 'Zookeeper',
    description: 'A handler or keeper of animals, familiar with enclosures, feeding, and the temper of beasts.',
    group: 'Manual Labor',
    skillPoints: 'EDU × 2 + DEX × 2',
    creditRatingRange: { min: 10, max: 40 },
    occupationalSkills: ['Animal Handling', 'Listen', 'Natural World', 'Spot Hidden', 'Track'],
    choiceGroups: [
      { count: 1, options: ['First Aid', 'Mechanical Repair', 'Ride'] },
      ...anySkill,
    ],
    source: 'Regency Cthulhu',
  },
];
