export const SKILL_SPECIALIZATIONS: Record<string, string[]> = {
    'Art and Craft': [
      'Acting',
      'Art Appreciation',
      'Blacksmithing',
      'Carpentry',
      'Cooking',
      'Business',
      'Embroidery',
      'Fine Art',
      'Forgery',
    'Piano',
    'Singing',
    'Violin',
    'Poetry',
    'Pottery',
    'Sculpture',
    'Sewing',
    'Writing',
  ],
  Fighting: [
    'Axe',
    'Brawl',
    'Flail',
    'Garrote',
    'Rapier',
    'Saber',
    'Spear',
    'Whip',
  ],
  Firearms: [
    'Bow',
    'Pistol',
    'Rifle/Blunderbuss',
  ],
  Language: [
    'Arabic',
    'French',
    'German',
    'Greek',
    'Italian',
    'Latin',
    'Spanish',
  ],
  Pilot: [
    'Boat',
  ],
  Survival: [
    'Country',
    'Sea',
    'Road',
  ],
};
