import type { DGItem } from '../../types';
import { normalizeItemName } from '../../utils';

// Regency scaffold: appendix B establishes the era weapon families and
// carriage-chase support. These entries keep the Equipment tab populated while
// the full occupation and shopping rules are expanded in later prompts.
export const WEAPONS_REGENCY: DGItem[] = [
  {
    section: 'Hand-to-Hand Weapons',
    name: normalizeItemName('Rapier'),
    skill: 'Fighting (Sword)',
    damage: '1D8+DB',
    range: 'Touch',
    uses: '1',
    price: '£2',
    sourceType: 'core',
    sourceName: 'Regency Cthulhu',
    sourcePage: null,
  },
  {
    section: 'Hand-to-Hand Weapons',
    name: normalizeItemName('Saber'),
    skill: 'Fighting (Sword)',
    damage: '1D8+DB',
    range: 'Touch',
    uses: '1',
    price: '£2',
    sourceType: 'core',
    sourceName: 'Regency Cthulhu',
    sourcePage: null,
  },
  {
    section: 'Hand-to-Hand Weapons',
    name: normalizeItemName('Whip'),
    skill: 'Fighting (Whip)',
    damage: '1D3+½DB',
    range: '10 ft',
    uses: '1',
    price: '10s',
    sourceType: 'core',
    sourceName: 'Regency Cthulhu',
    sourcePage: null,
  },
  {
    section: 'Hand-to-Hand Weapons',
    name: normalizeItemName('Cane Sword'),
    skill: 'Fighting (Sword)',
    damage: '1D8+DB',
    range: 'Touch',
    uses: '1',
    price: '£3',
    sourceType: 'core',
    sourceName: 'Regency Cthulhu',
    sourcePage: null,
  },
  {
    section: 'Hand-to-Hand Weapons',
    name: normalizeItemName('Dagger'),
    skill: 'Fighting (Brawl)',
    damage: '1D4+DB',
    range: 'Touch',
    uses: '1',
    price: '5s',
    sourceType: 'core',
    sourceName: 'Regency Cthulhu',
    sourcePage: null,
  },
  {
    section: 'Archaic Ranged Weapons',
    name: normalizeItemName('Bow and Arrows'),
    skill: 'Firearms (Bow)',
    damage: '1D6+½DB',
    range: '30 yd',
    uses: '1',
    price: '£1',
    sourceType: 'core',
    sourceName: 'Regency Cthulhu',
    sourcePage: null,
  },
  {
    section: 'Firearms',
    name: normalizeItemName('Flintlock Pistol'),
    skill: 'Firearms (Pistol)',
    damage: '1D10',
    range: '20 yd',
    uses: '1',
    ammoCapacity: '1',
    armorPiercing: '95',
    price: '£4',
    sourceType: 'core',
    sourceName: 'Regency Cthulhu',
    sourcePage: null,
  },
  {
    section: 'Firearms',
    name: normalizeItemName('Dueling Pistol'),
    skill: 'Firearms (Pistol)',
    damage: '1D10',
    range: '20 yd',
    uses: '1',
    ammoCapacity: '1',
    armorPiercing: '95',
    price: '£5',
    sourceType: 'core',
    sourceName: 'Regency Cthulhu',
    sourcePage: null,
  },
  {
    section: 'Firearms',
    name: normalizeItemName('Musket'),
    skill: 'Firearms (Rifle/Blunderbuss)',
    damage: '1D10',
    range: '40/80 yd',
    uses: '1',
    ammoCapacity: '1',
    armorPiercing: '100',
    price: '£6',
    sourceType: 'core',
    sourceName: 'Regency Cthulhu',
    sourcePage: null,
    description: 'May also be loaded with shot instead of a musket ball; if so, apply blunderbuss-style damage at a longer range.',
  },
  {
    section: 'Firearms',
    name: normalizeItemName('Blunderbuss'),
    skill: 'Firearms (Rifle/Blunderbuss)',
    damage: '2D6',
    range: '5/10 yd',
    uses: '1',
    ammoCapacity: '1',
    armorPiercing: '100',
    price: '£5',
    sourceType: 'core',
    sourceName: 'Regency Cthulhu',
    sourcePage: null,
  },
  {
    section: 'Firearms',
    name: normalizeItemName('Horse Pistol'),
    skill: 'Firearms (Pistol)',
    damage: '1D10',
    range: '20 yd',
    uses: '1',
    ammoCapacity: '1',
    armorPiercing: '95',
    price: '£4',
    sourceType: 'core',
    sourceName: 'Regency Cthulhu',
    sourcePage: null,
  },
  {
    section: 'Carriages & Chases',
    name: normalizeItemName('Phaeton'),
    price: '£60',
    description: 'Light, fashionable carriage. Open or closed; useful for fast travel and chase scenes.',
    sourceType: 'core',
    sourceName: 'Regency Cthulhu',
    sourcePage: null,
  },
  {
    section: 'Carriages & Chases',
    name: normalizeItemName('Curricle'),
    price: '£45',
    description: 'A sporty two-wheeled carriage for rapid travel.',
    sourceType: 'core',
    sourceName: 'Regency Cthulhu',
    sourcePage: null,
  },
  {
    section: 'Carriages & Chases',
    name: normalizeItemName('Gig'),
    price: '£35',
    description: 'A compact two-wheeled carriage for one or two travelers.',
    sourceType: 'core',
    sourceName: 'Regency Cthulhu',
    sourcePage: null,
  },
  {
    section: 'Carriages & Chases',
    name: normalizeItemName('Barouche'),
    price: '£85',
    description: 'A larger open carriage suited to formal travel and social display.',
    sourceType: 'core',
    sourceName: 'Regency Cthulhu',
    sourcePage: null,
  },
  {
    section: 'Carriages & Chases',
    name: normalizeItemName('Landau'),
    price: '£120',
    description: 'A luxurious four-wheeled carriage with open or closed options.',
    sourceType: 'core',
    sourceName: 'Regency Cthulhu',
    sourcePage: null,
  },
  {
    section: 'Carriages & Chases',
    name: normalizeItemName('Brougham'),
    price: '£90',
    description: 'A closed carriage designed for discreet town travel.',
    sourceType: 'core',
    sourceName: 'Regency Cthulhu',
    sourcePage: null,
  },
  {
    section: 'Carriages & Chases',
    name: normalizeItemName('Post Chaise'),
    price: '£35',
    description: 'A hired carriage used for speed on long roads with fresh horses at posting inns.',
    sourceType: 'core',
    sourceName: 'Regency Cthulhu',
    sourcePage: null,
  },
  {
    section: 'Carriages & Chases',
    name: normalizeItemName('Hansom Cab'),
    price: '£20',
    description: 'A two-wheeled cab for hire in towns and cities.',
    sourceType: 'core',
    sourceName: 'Regency Cthulhu',
    sourcePage: null,
  },
];
