import type { Skill } from '../../types';

export const SKILLS: Skill[] = [
  // Core skills from Classic 1920s (excluding Drive Auto, Electrical Repair, Psychoanalysis)
  { name: 'Accounting', base: 5, description: "Track finances, spot irregularities, and create false accounts." },
  { name: 'Anthropology', base: 1, description: "Understand human cultures, behaviors, and beliefs, particularly in primitive or exotic societies." },
  { name: 'Appraise', base: 5, description: "Estimate the value of an item, and spot fakes and forgeries." },
  { name: 'Archaeology', base: 1, description: "Study ancient cultures through their physical remains, artifacts, and ruins." },
  { name: 'Art and Craft', base: 5, specialty: true, description: "Create a work of art or a craft. Can also be used to identify forgeries or repair items." },
  { name: 'Charm', base: 15, description: "Influence others through flattery, wit, and grace. A social skill for making friends and allies." },
  { name: 'Climb', base: 20, description: "Ascend or descend difficult surfaces like walls, trees, or cliffs." },
  { name: 'Credit Rating', base: 0, description: "Represents an investigator's wealth and social standing." },
  { name: 'Cthulhu Mythos', base: 0, description: "Forbidden knowledge of the alien and monstrous forces that lurk at the edge of reality. This skill can only be increased by direct, sanity-shattering experience." },
  { name: 'Disguise', base: 5, description: "Alter one's appearance to be unrecognizable or to impersonate someone else." },
  { name: 'Dodge', base: 0, description: "Automatically avoid a blow or thrown weapon. Base value is half of DEX." },
  { name: 'Fast Talk', base: 5, description: "Convince others with fast, confusing, or plausible-sounding lies. A social skill for deception." },
  { name: 'Fighting', base: 25, specialty: true, description: "Engage in hand-to-hand combat, from simple brawling to mastery of specific melee weapons." },
  { name: 'Firearms', base: 20, specialty: true, description: "Use firearms effectively in combat, from pistols to rifles and shotguns." },
  { name: 'First Aid', base: 30, description: "Provide immediate medical care to stabilize an injury and prevent death." },
  { name: 'History', base: 5, description: "Recall historical events, figures, and contexts." },
  { name: 'Intimidate', base: 15, description: "Influence others through threats, force of personality, or overt menace. A social skill for coercion." },
  { name: 'Jump', base: 20, description: "Leap across gaps or over obstacles." },
  { name: 'Language (Other)', base: 1, specialty: true, stub: 'Language', description: "Speak, read, and write in a language other than your own." },
  { name: 'Language (Own)', base: 0, description: "The investigator's proficiency with their native language. Base value is equal to EDU." },
  { name: 'Law', base: 5, description: "Represents the chance of knowing pertinent law, precedent, legal maneuvers, or court procedure. It helps when dealing with the police, lawyers, and courts." },
  { name: 'Library Use', base: 20, description: "Efficiently find information in libraries, archives, and other repositories of records." },
  { name: 'Listen', base: 20, description: "Hear faint or indistinct sounds and interpret their meaning." },
  { name: 'Locksmith', base: 1, description: "Pick locks and bypass physical security." },
  { name: 'Mechanical Repair', base: 10, description: "Repair or jury-rig mechanical devices." },
  { name: 'Medicine', base: 1, description: "Diagnose and treat illnesses and severe injuries. Can perform surgery." },
  { name: 'Natural World', base: 10, description: "Knowledge of flora, fauna, weather patterns, and natural phenomena. Important for craftspeople, screevers (forgers), and outdoor workers before urbanization." },
  { name: 'Navigate', base: 10, specialty: true, description: "Find your way with or without maps, by stars, or by natural signs. Can be specialized by location (e.g., Own City)." },
  { name: 'Occult', base: 5, description: "Knowledge of fringe beliefs, secret societies, and folklore concerning the supernatural." },
  { name: 'Operate Heavy Machinery', base: 1, description: "Use heavy equipment like a steam shovel, tractor, or industrial machinery." },
  { name: 'Persuade', base: 10, description: "Influence others with reasoned argument, debate, or heartfelt appeal. A social skill for honest conviction." },
  { name: 'Pilot', base: 1, specialty: true, description: "Operate a specific type of complex vehicle, such as an airplane or boat." },
  { name: 'Psychology', base: 10, description: "Understand the motivations and mental state of another person through observation and interaction." },
  { name: 'Ride', base: 5, description: "Ride and control a mount, such as a horse or camel." },
  { name: 'Science', base: 1, specialty: true, description: "Knowledge in a specific field of science, such as chemistry, physics, biology, engineering, or pharmacy." },
  { name: 'Sleight of Hand', base: 10, description: "Perform feats of manual dexterity, such as pickpocketing or palming an object." },
  { name: 'Spot Hidden', base: 25, description: "Notice things that are concealed, overlooked, or out of the ordinary." },
  { name: 'Stealth', base: 20, description: "Move without being seen or heard." },
  { name: 'Survival', base: 10, specialty: true, description: "Survive in a specific type of harsh environment (e.g., Desert, Arctic)." },
  { name: 'Swim', base: 20, description: "Stay afloat and move through water." },
  { name: 'Throw', base: 20, description: "Accurately throw an object." },
  { name: 'Track', base: 10, description: "Follow the tracks of a person or creature." },

  // New skills specific to Gaslight 1890s era
  { name: 'Alienism', base: 1, description: "The Victorian-era study of mental illness, equivalent to what would later become Psychoanalysis in the 1920s. Used by physicians treating mental disorders." },
  { name: 'Artillery (Rocket)', base: 1, description: "An uncommon skill that assumes some form of military training and experience. The user has experience operating field weapons in warfare and working in a crew to operate the projection of munitions beyond the range of personal weapons. This skill roll cannot be pushed." },
  { name: 'Diving', base: 1, description: "An uncommon skill for diving and swimming underwater, such as freediving to gather food or explore the undersea realm. Encompasses use of diving bells—rigid chambers to aid undersea activities—as well as Victorian diving suits. Prior to the invention of the Aqua-Lung in 1942, divers wore rigid suits with air pumped from the surface through a connecting tube." },
  { name: 'Electrical Repair', base: 1, description: "Repair or reconfigure electrical equipment, such as electric lights, gramophone record players, telegraph machines, and so on." },
  { name: 'Mesmerism', base: 1, description: "An uncommon skill that replaces the Hypnosis skill in 1920s and modern-day games. The user can induce a trance-like state in a target, causing heightened suggestibility, relaxation, and possibly recall of forgotten memories. This is an opposed roll between Mesmerism and the target's POW or Psychology, although with a willing target, only a successful Mesmerism roll is needed. Only one target at a time can be under the effects of Mesmerism." },
  { name: 'Psychic', base: 0, description: "This skill is not a standard Call of Cthulhu skill, and instead refers to a special skill that can be used in games using the Pulp Cthulhu rules supplement—see that book if you wish to use psychic powers and enjoy a pulpier style of play." },
  { name: 'Read Lips', base: 1, description: "An uncommon skill enabling the user to listen in on a conversation without requiring them to hear the speakers. Line of sight is necessary, and if only one speaker's lips can be seen, only their words (not the whole conversation) can be deciphered. Two characters proficient in Read Lips may use the skill to communicate silently with one another." },
  { name: 'Reassure', base: 0, description: "While psychoanalysis has yet to be invented, calm words and intuitive insight from a caring person with a friendly face can work wonders for soothing a troubled mind. A successful Reassure roll enables the recipient to recover +2 Sanity points (cannot exceed maximum SAN). Each investigator can benefit from this only once per scenario or campaign chapter. Base value is one-fifth APP." },
  { name: 'Animal Handling', base: 5, description: "Essential for working with horses, livestock, and other animals in the pre-automotive age. Common among blacksmiths, cabbies, laborers, and explorers." },
  { name: 'Artillery', base: 1, specialty: true, description: "Military knowledge of cannons, mortars, and other heavy weapons. Available to ex-military enlisted personnel and NCOs." },
  { name: 'Demolitions', base: 1, description: "Expertise in explosives and controlled destruction. Used by navvies (railway builders) and specialized military personnel." },
  { name: 'Drive Carriage', base: 20, description: "The Victorian equivalent of Drive Auto, covering horse-drawn vehicles from hansom cabs to four-in-hand coaches. Essential for cabbies, servants, and laborers." },
  { name: 'Lore', base: 1, specialty: true, description: "Specialized knowledge about a specific location, culture, or subject (e.g., London, Ireland, China)." },
  { name: 'Religion', base: 10, specialty: true, description: "Knowledge of human religions, belief systems, and mythologies, covering doctrine, practice, and history of traditions. The core Religion skill focuses on understanding of the 'main world religions' such as Christianity, Judaism, Hinduism, Islam, Buddhism, Shinto, Sikhism, and so forth. Additional specialties in specific religions or belief systems falling outside the 'main world religions' are available, such as Celtic Paganism, Berber, Cherokee, and so on." }
];
