// Gaslight Era (1890s) Weapons Data - Complete Implementation
// Based on official Cthulhu by Gaslight sourcebook Tables 18-23

export type WeaponRec = {
  name: string;
  skill: string;
  specialization: string | null;
  damage: string;
  base_range: string;
  base_range_yards: number | null;
  uses_per_round: string;
  uses_per_round_int: number | null;
  mag: string;
  mag_int: number | null;
  cost: { gaslight: number | null; modern: number | null };
  malfunction: string;
  eras: string[];
  category: string;
  source: { book: string; page: number | null };
};

export const WEAPONS_GASLIGHT: WeaponRec[] = [
  // Table 18: Hand-to-Hand Weapons (Melee)
  {
    name: "Blackjack/Life Preserver",
    skill: "Fighting",
    specialization: "Brawl",
    damage: "1D8+DB*",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { gaslight: 48, modern: null },
    malfunction: "—",
    eras: ["gaslight-1890s"],
    category: "Hand-to-Hand Weapons",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Burning Torch",
    skill: "Fighting",
    specialization: "Brawl",
    damage: "1D6+burn",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { gaslight: null, modern: null },
    malfunction: "—",
    eras: ["gaslight-1890s"],
    category: "Hand-to-Hand Weapons",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Cavalry Lance",
    skill: "Fighting",
    specialization: "Spear",
    damage: "1D8+1",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { gaslight: 360, modern: null },
    malfunction: "—",
    eras: ["gaslight-1890s"],
    category: "Hand-to-Hand Weapons",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Cavalry Saber",
    skill: "Fighting",
    specialization: "Sword",
    damage: "1D8+1+DB",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { gaslight: 240, modern: null },
    malfunction: "—",
    eras: ["gaslight-1890s"],
    category: "Hand-to-Hand Weapons",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Club, Large (cricket bat, poker)",
    skill: "Fighting",
    specialization: "Brawl",
    damage: "1D8+DB",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { gaslight: 165, modern: null },
    malfunction: "—",
    eras: ["gaslight-1890s"],
    category: "Hand-to-Hand Weapons",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Club, Small (truncheon)",
    skill: "Fighting",
    specialization: "Brawl",
    damage: "1D6+DB",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { gaslight: 48, modern: null },
    malfunction: "—",
    eras: ["gaslight-1890s"],
    category: "Hand-to-Hand Weapons",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Fencing Foil, Sharpened",
    skill: "Fighting",
    specialization: "Sword",
    damage: "1D6+DB",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { gaslight: 30, modern: null },
    malfunction: "—",
    eras: ["gaslight-1890s"],
    category: "Hand-to-Hand Weapons",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Garotte",
    skill: "Fighting",
    specialization: "Garotte",
    damage: "1D6+DB",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { gaslight: null, modern: null },
    malfunction: "—",
    eras: ["gaslight-1890s"],
    category: "Hand-to-Hand Weapons",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Hairpin, 7\"",
    skill: "Fighting",
    specialization: "Brawl",
    damage: "1D4+DB",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { gaslight: 12, modern: null },
    malfunction: "—",
    eras: ["gaslight-1890s"],
    category: "Hand-to-Hand Weapons",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Hand Sickle",
    skill: "Fighting",
    specialization: "Axe",
    damage: "1D6+1+DB",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { gaslight: 12, modern: null },
    malfunction: "—",
    eras: ["gaslight-1890s"],
    category: "Hand-to-Hand Weapons",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Hatchet",
    skill: "Fighting",
    specialization: "Axe",
    damage: "1D6+1+DB",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { gaslight: 38, modern: null },
    malfunction: "—",
    eras: ["gaslight-1890s"],
    category: "Hand-to-Hand Weapons",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Horsewhip",
    skill: "Fighting",
    specialization: "Whip",
    damage: "1D3+½DB",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { gaslight: 204, modern: null },
    malfunction: "—",
    eras: ["gaslight-1890s"],
    category: "Hand-to-Hand Weapons",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Knife, Large (cleaver)",
    skill: "Fighting",
    specialization: "Brawl",
    damage: "1D8+DB",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { gaslight: 15, modern: null },
    malfunction: "—",
    eras: ["gaslight-1890s"],
    category: "Hand-to-Hand Weapons",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Knife, Medium (hunting)",
    skill: "Fighting",
    specialization: "Brawl",
    damage: "1D4+2+DB",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { gaslight: 156, modern: null },
    malfunction: "—",
    eras: ["gaslight-1890s"],
    category: "Hand-to-Hand Weapons",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Knife, Small (pocket)",
    skill: "Fighting",
    specialization: "Brawl",
    damage: "1D4+DB",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { gaslight: 12, modern: null },
    malfunction: "—",
    eras: ["gaslight-1890s"],
    category: "Hand-to-Hand Weapons",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Rapier/Heavy Épée",
    skill: "Fighting",
    specialization: "Sword",
    damage: "1D6+1+DB",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { gaslight: 240, modern: null },
    malfunction: "—",
    eras: ["gaslight-1890s"],
    category: "Hand-to-Hand Weapons",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Scythe",
    skill: "Fighting",
    specialization: "Brawl",
    damage: "1D6+1+DB",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { gaslight: 48, modern: null },
    malfunction: "—",
    eras: ["gaslight-1890s"],
    category: "Hand-to-Hand Weapons",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Straight Razor",
    skill: "Fighting",
    specialization: "Brawl",
    damage: "1D4+DB",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { gaslight: 42, modern: null },
    malfunction: "—",
    eras: ["gaslight-1890s"],
    category: "Hand-to-Hand Weapons",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Sword Cane",
    skill: "Fighting",
    specialization: "Sword",
    damage: "1D6+DB",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { gaslight: 276, modern: null },
    malfunction: "—",
    eras: ["gaslight-1890s"],
    category: "Hand-to-Hand Weapons",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Thrown Rock",
    skill: "Throw",
    specialization: null,
    damage: "1D4+½DB",
    base_range: "STR/5 yards",
    base_range_yards: null,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { gaslight: null, modern: null },
    malfunction: "—",
    eras: ["gaslight-1890s"],
    category: "Hand-to-Hand Weapons",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Thrown Spear (javelin)",
    skill: "Throw",
    specialization: null,
    damage: "1D8+½DB",
    base_range: "STR/5 yards",
    base_range_yards: null,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { gaslight: 132, modern: null },
    malfunction: "—",
    eras: ["gaslight-1890s"],
    category: "Hand-to-Hand Weapons",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Wood Axe",
    skill: "Fighting",
    specialization: "Axe",
    damage: "1D8+2+DB",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { gaslight: 60, modern: null },
    malfunction: "—",
    eras: ["gaslight-1890s"],
    category: "Hand-to-Hand Weapons",
    source: { book: "Gaslight Victorian Era", page: null }
  },

  // Archaic Ranged Weapons
  {
    name: "Archery Bow",
    skill: "Firearms",
    specialization: "Bow",
    damage: "1D6+½DB",
    base_range: "30 yards",
    base_range_yards: 30,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "1",
    mag_int: 1,
    cost: { gaslight: 408, modern: null },
    malfunction: "97",
    eras: ["gaslight-1890s"],
    category: "Archaic Ranged Weapons",
    source: { book: "Gaslight Victorian Era", page: null }
  },

  // Table 19: Handguns
  {
    name: ".22 Revolver",
    skill: "Firearms",
    specialization: "Handgun",
    damage: "1D6",
    base_range: "10 yards",
    base_range_yards: 10,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "7",
    mag_int: 7,
    cost: { gaslight: 300, modern: null },
    malfunction: "99",
    eras: ["gaslight-1890s"],
    category: "Handguns (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".32 Revolver",
    skill: "Firearms",
    specialization: "Handgun",
    damage: "1D8",
    base_range: "15 yards",
    base_range_yards: 15,
    uses_per_round: "1(3)",
    uses_per_round_int: 3,
    mag: "6",
    mag_int: 6,
    cost: { gaslight: 504, modern: null },
    malfunction: "99",
    eras: ["gaslight-1890s"],
    category: "Handguns (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "M1895 Nagant 7.62mm",
    skill: "Firearms",
    specialization: "Handgun",
    damage: "1D8",
    base_range: "15 yards",
    base_range_yards: 15,
    uses_per_round: "1(3)",
    uses_per_round_int: 3,
    mag: "7",
    mag_int: 7,
    cost: { gaslight: 1020, modern: null },
    malfunction: "99",
    eras: ["gaslight-1890s"],
    category: "Handguns (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "7.65mm Automatic",
    skill: "Firearms",
    specialization: "Handgun",
    damage: "1D8+1",
    base_range: "15 yards",
    base_range_yards: 15,
    uses_per_round: "1(3)",
    uses_per_round_int: 3,
    mag: "8",
    mag_int: 8,
    cost: { gaslight: 1440, modern: null },
    malfunction: "96",
    eras: ["gaslight-1890s"],
    category: "Handguns (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".38 Revolver",
    skill: "Firearms",
    specialization: "Handgun",
    damage: "1D10",
    base_range: "15 yards",
    base_range_yards: 15,
    uses_per_round: "1(3)",
    uses_per_round_int: 3,
    mag: "6",
    mag_int: 6,
    cost: { gaslight: 840, modern: null },
    malfunction: "99",
    eras: ["gaslight-1890s"],
    category: "Handguns (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Modele 1892 8mm Revolver",
    skill: "Firearms",
    specialization: "Handgun",
    damage: "1D8+2",
    base_range: "15 yards",
    base_range_yards: 15,
    uses_per_round: "1(3)",
    uses_per_round_int: 3,
    mag: "6",
    mag_int: 6,
    cost: { gaslight: 540, modern: null },
    malfunction: "99",
    eras: ["gaslight-1890s"],
    category: "Handguns (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".41 Colt Derringer",
    skill: "Firearms",
    specialization: "Handgun",
    damage: "1D10",
    base_range: "15 yards",
    base_range_yards: 15,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "1",
    mag_int: 1,
    cost: { gaslight: 252, modern: null },
    malfunction: "99",
    eras: ["gaslight-1890s"],
    category: "Handguns (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".41 Remington 2-shot",
    skill: "Firearms",
    specialization: "Handgun",
    damage: "1D10+1",
    base_range: "3 yards",
    base_range_yards: 3,
    uses_per_round: "1(2)",
    uses_per_round_int: 2,
    mag: "2",
    mag_int: 2,
    cost: { gaslight: 240, modern: null },
    malfunction: "99",
    eras: ["gaslight-1890s"],
    category: "Handguns (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".41 Revolver",
    skill: "Firearms",
    specialization: "Handgun",
    damage: "1D10",
    base_range: "3 yards",
    base_range_yards: 3,
    uses_per_round: "1(3)",
    uses_per_round_int: 3,
    mag: "6",
    mag_int: 6,
    cost: { gaslight: 1032, modern: null },
    malfunction: "99",
    eras: ["gaslight-1890s"],
    category: "Handguns (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".44 Henry/Colt",
    skill: "Firearms",
    specialization: "Handgun",
    damage: "2D6+1",
    base_range: "15 yards",
    base_range_yards: 15,
    uses_per_round: "1(3)",
    uses_per_round_int: 3,
    mag: "6",
    mag_int: 6,
    cost: { gaslight: 1056, modern: null },
    malfunction: "99",
    eras: ["gaslight-1890s"],
    category: "Handguns (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".44-40 Winchester",
    skill: "Firearms",
    specialization: "Handgun",
    damage: "2D6+1",
    base_range: "15 yards",
    base_range_yards: 15,
    uses_per_round: "1(3)",
    uses_per_round_int: 3,
    mag: "6",
    mag_int: 6,
    cost: { gaslight: 1056, modern: null },
    malfunction: "99",
    eras: ["gaslight-1890s"],
    category: "Handguns (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".45/.455 Webley/Colt",
    skill: "Firearms",
    specialization: "Handgun",
    damage: "1D10+2",
    base_range: "15 yards",
    base_range_yards: 15,
    uses_per_round: "1(3)",
    uses_per_round_int: 3,
    mag: "6",
    mag_int: 6,
    cost: { gaslight: 1200, modern: null },
    malfunction: "99",
    eras: ["gaslight-1890s"],
    category: "Handguns (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".45 British Bulldog",
    skill: "Firearms",
    specialization: "Handgun",
    damage: "1D10+1",
    base_range: "15 yards",
    base_range_yards: 15,
    uses_per_round: "1(3)",
    uses_per_round_int: 3,
    mag: "5",
    mag_int: 5,
    cost: { gaslight: 504, modern: null },
    malfunction: "99",
    eras: ["gaslight-1890s"],
    category: "Handguns (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".476 Revolver",
    skill: "Firearms",
    specialization: "Handgun",
    damage: "2D6+2",
    base_range: "15 yards",
    base_range_yards: 15,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "5",
    mag_int: 5,
    cost: { gaslight: 1200, modern: null },
    malfunction: "96",
    eras: ["gaslight-1890s"],
    category: "Handguns (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".577 Lancaster Pistol",
    skill: "Firearms",
    specialization: "Handgun",
    damage: "2D6+3",
    base_range: "15 yards",
    base_range_yards: 15,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "2 or 4",
    mag_int: 4,
    cost: { gaslight: 1920, modern: null },
    malfunction: "99",
    eras: ["gaslight-1890s"],
    category: "Handguns (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Borchardt C-93 Automatic",
    skill: "Firearms",
    specialization: "Handgun",
    damage: "1D8+1",
    base_range: "15 yards",
    base_range_yards: 15,
    uses_per_round: "1(3)",
    uses_per_round_int: 3,
    mag: "8",
    mag_int: 8,
    cost: { gaslight: 2400, modern: null },
    malfunction: "96",
    eras: ["gaslight-1890s"],
    category: "Handguns (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Mauser C96 Automatic",
    skill: "Firearms",
    specialization: "Handgun",
    damage: "1D8+1",
    base_range: "15 yards",
    base_range_yards: 15,
    uses_per_round: "1(3)",
    uses_per_round_int: 3,
    mag: "10",
    mag_int: 10,
    cost: { gaslight: 1920, modern: null },
    malfunction: "96",
    eras: ["gaslight-1890s"],
    category: "Handguns (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },

  // Table 20: Rifles  
  {
    name: ".46 Air Rifle",
    skill: "Firearms",
    specialization: "Rifle",
    damage: "2D6+1",
    base_range: "30 yards",
    base_range_yards: 30,
    uses_per_round: "1/2",
    uses_per_round_int: null,
    mag: "1",
    mag_int: 1,
    cost: { gaslight: 480, modern: null },
    malfunction: "88",
    eras: ["gaslight-1890s"],
    category: "Rifles (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".410 Cane Gun (ball)",
    skill: "Firearms",
    specialization: "Rifle",
    damage: "1D10+1",
    base_range: "5 yards",
    base_range_yards: 5,
    uses_per_round: "1/3",
    uses_per_round_int: null,
    mag: "1",
    mag_int: 1,
    cost: { gaslight: 300, modern: null },
    malfunction: "99",
    eras: ["gaslight-1890s"],
    category: "Rifles (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".410 Bore (2B) (ball)",
    skill: "Firearms",
    specialization: "Rifle",
    damage: "1D10+1",
    base_range: "10 yards",
    base_range_yards: 10,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "2",
    mag_int: 2,
    cost: { gaslight: 960, modern: null },
    malfunction: "99",
    eras: ["gaslight-1890s"],
    category: "Rifles (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Ball & Shot Gun (2B) (ball)",
    skill: "Firearms",
    specialization: "Rifle",
    damage: "3D6+4",
    base_range: "80 yards",
    base_range_yards: 80,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "2",
    mag_int: 2,
    cost: { gaslight: 13104, modern: null },
    malfunction: "99",
    eras: ["gaslight-1890s"],
    category: "Rifles (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".22 Winchester 1890",
    skill: "Firearms",
    specialization: "Rifle",
    damage: "1D6+1",
    base_range: "30 yards",
    base_range_yards: 30,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "22",
    mag_int: 22,
    cost: { gaslight: 744, modern: null },
    malfunction: "98",
    eras: ["gaslight-1890s"],
    category: "Rifles (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".22 Remington Rifle Cane",
    skill: "Firearms",
    specialization: "Rifle",
    damage: "1D6",
    base_range: "15 yards",
    base_range_yards: 15,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "1 or 3",
    mag_int: 3,
    cost: { gaslight: 420, modern: null },
    malfunction: "98",
    eras: ["gaslight-1890s"],
    category: "Rifles (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".30 Lever Action",
    skill: "Firearms",
    specialization: "Rifle",
    damage: "2D6",
    base_range: "50 yards",
    base_range_yards: 50,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "6",
    mag_int: 6,
    cost: { gaslight: 1080, modern: null },
    malfunction: "98",
    eras: ["gaslight-1890s"],
    category: "Rifles (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".300 (2B)",
    skill: "Firearms",
    specialization: "Rifle",
    damage: "2D6+4",
    base_range: "110 yards",
    base_range_yards: 110,
    uses_per_round: "1 or 2",
    uses_per_round_int: 2,
    mag: "2",
    mag_int: 2,
    cost: { gaslight: 1140, modern: null },
    malfunction: "99",
    eras: ["gaslight-1890s"],
    category: "Rifles (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".303 Lee Metford/Enfield",
    skill: "Firearms",
    specialization: "Rifle",
    damage: "2D6+4",
    base_range: "110 yards",
    base_range_yards: 110,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "10",
    mag_int: 10,
    cost: { gaslight: 1800, modern: null },
    malfunction: "99",
    eras: ["gaslight-1890s"],
    category: "Rifles (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".30-40 Springfield M1892",
    skill: "Firearms",
    specialization: "Rifle",
    damage: "2D6+4",
    base_range: "110 yards",
    base_range_yards: 110,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "5",
    mag_int: 5,
    cost: { gaslight: 3720, modern: null },
    malfunction: "99",
    eras: ["gaslight-1890s"],
    category: "Rifles (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "8mm Mauser Gewehr",
    skill: "Firearms",
    specialization: "Rifle",
    damage: "2D6+4",
    base_range: "110 yards",
    base_range_yards: 110,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "5",
    mag_int: 5,
    cost: { gaslight: 1680, modern: null },
    malfunction: "99",
    eras: ["gaslight-1890s"],
    category: "Rifles (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".44 Lever or Slide Action",
    skill: "Firearms",
    specialization: "Rifle",
    damage: "2D6+1",
    base_range: "50 yards",
    base_range_yards: 50,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "15",
    mag_int: 15,
    cost: { gaslight: 1236, modern: null },
    malfunction: "98",
    eras: ["gaslight-1890s"],
    category: "Rifles (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".44 Henry Repeating",
    skill: "Firearms",
    specialization: "Rifle",
    damage: "2D6",
    base_range: "50 yards",
    base_range_yards: 50,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "16",
    mag_int: 16,
    cost: { gaslight: 1008, modern: null },
    malfunction: "98",
    eras: ["gaslight-1890s"],
    category: "Rifles (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".44-40 Winchester '73 Rifle",
    skill: "Firearms",
    specialization: "Rifle",
    damage: "2D6+1",
    base_range: "80 yards",
    base_range_yards: 80,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "15",
    mag_int: 15,
    cost: { gaslight: 1200, modern: null },
    malfunction: "98",
    eras: ["gaslight-1890s"],
    category: "Rifles (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".44-40 Winchester '73 Carbine",
    skill: "Firearms",
    specialization: "Rifle",
    damage: "2D6+1",
    base_range: "50 yards",
    base_range_yards: 50,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "12",
    mag_int: 12,
    cost: { gaslight: 1200, modern: null },
    malfunction: "98",
    eras: ["gaslight-1890s"],
    category: "Rifles (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".45-70 Springfield Trapdoor",
    skill: "Firearms",
    specialization: "Rifle",
    damage: "2D6+2",
    base_range: "100 yards",
    base_range_yards: 100,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "1",
    mag_int: 1,
    cost: { gaslight: 816, modern: null },
    malfunction: "99",
    eras: ["gaslight-1890s"],
    category: "Rifles (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".45-75 Winchester '76 Rifle",
    skill: "Firearms",
    specialization: "Rifle",
    damage: "2D6+3",
    base_range: "80 yards",
    base_range_yards: 80,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "10",
    mag_int: 10,
    cost: { gaslight: 1296, modern: null },
    malfunction: "98",
    eras: ["gaslight-1890s"],
    category: "Rifles (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".45-75 Winchester '76 Carbine",
    skill: "Firearms",
    specialization: "Rifle",
    damage: "2D6+3",
    base_range: "50 yards",
    base_range_yards: 50,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "8",
    mag_int: 8,
    cost: { gaslight: 1296, modern: null },
    malfunction: "98",
    eras: ["gaslight-1890s"],
    category: "Rifles (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".577/.450 Martini Henry",
    skill: "Firearms",
    specialization: "Rifle",
    damage: "1D8+1D6+3",
    base_range: "80 yards",
    base_range_yards: 80,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "1",
    mag_int: 1,
    cost: { gaslight: 1920, modern: null },
    malfunction: "99",
    eras: ["gaslight-1890s"],
    category: "Rifles (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".500 Express (2B)",
    skill: "Firearms",
    specialization: "Rifle",
    damage: "3D6+4",
    base_range: "100 yards",
    base_range_yards: 100,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "2",
    mag_int: 2,
    cost: { gaslight: 10800, modern: null },
    malfunction: "99",
    eras: ["gaslight-1890s"],
    category: "Rifles (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".52 Sharps Rifle",
    skill: "Firearms",
    specialization: "Rifle",
    damage: "2D6+2",
    base_range: "80 yards",
    base_range_yards: 80,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "1",
    mag_int: 1,
    cost: { gaslight: 816, modern: null },
    malfunction: "98",
    eras: ["gaslight-1890s"],
    category: "Rifles (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".52 Sharps Carbine",
    skill: "Firearms",
    specialization: "Rifle",
    damage: "2D6+2",
    base_range: "50 yards",
    base_range_yards: 50,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "1",
    mag_int: 1,
    cost: { gaslight: 768, modern: null },
    malfunction: "98",
    eras: ["gaslight-1890s"],
    category: "Rifles (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".58 Springfield Rifle",
    skill: "Firearms",
    specialization: "Rifle",
    damage: "1D10+4",
    base_range: "60 yards",
    base_range_yards: 60,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "1",
    mag_int: 1,
    cost: { gaslight: 720, modern: null },
    malfunction: "95",
    eras: ["gaslight-1890s"],
    category: "Rifles (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".56 Spencer Carbine",
    skill: "Firearms",
    specialization: "Rifle",
    damage: "2D6+3",
    base_range: "50 yards",
    base_range_yards: 50,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "8",
    mag_int: 8,
    cost: { gaslight: 1152, modern: null },
    malfunction: "98",
    eras: ["gaslight-1890s"],
    category: "Rifles (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: ".50-70 Springfield Trapdoor",
    skill: "Firearms",
    specialization: "Rifle",
    damage: "2D6+4",
    base_range: "90 yards",
    base_range_yards: 90,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "1",
    mag_int: 1,
    cost: { gaslight: 816, modern: null },
    malfunction: "99",
    eras: ["gaslight-1890s"],
    category: "Rifles (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Buffalo Rifle",
    skill: "Firearms",
    specialization: "Rifle",
    damage: "3D6",
    base_range: "100 yards",
    base_range_yards: 100,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "1",
    mag_int: 1,
    cost: { gaslight: 1200, modern: null },
    malfunction: "99",
    eras: ["gaslight-1890s"],
    category: "Rifles (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Elephant Gun (1 or 2B)",
    skill: "Firearms",
    specialization: "Rifle",
    damage: "3D6+4",
    base_range: "100 yards",
    base_range_yards: 100,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "1 or 2",
    mag_int: 2,
    cost: { gaslight: 10800, modern: null },
    malfunction: "100",
    eras: ["gaslight-1890s"],
    category: "Rifles (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Sharps \"Big .50\"",
    skill: "Firearms",
    specialization: "Rifle",
    damage: "3D6",
    base_range: "100 yards",
    base_range_yards: 100,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "1",
    mag_int: 1,
    cost: { gaslight: 1056, modern: null },
    malfunction: "99",
    eras: ["gaslight-1890s"],
    category: "Rifles (i)*",
    source: { book: "Gaslight Victorian Era", page: null }
  },

  // Table 21: Shotguns
  {
    name: "20-Bore (2B)",
    skill: "Firearms",
    specialization: "Shotgun",
    damage: "2D6/1D6/1D3",
    base_range: "10/20/50 yards",
    base_range_yards: 50,
    uses_per_round: "1 or 2",
    uses_per_round_int: 2,
    mag: "2",
    mag_int: 2,
    cost: { gaslight: 756, modern: null },
    malfunction: "100",
    eras: ["gaslight-1890s"],
    category: "Shotguns*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "16-Bore Pump-Action",
    skill: "Firearms",
    specialization: "Shotgun",
    damage: "2D6+2/1D6+1/1D4",
    base_range: "10/20/50 yards",
    base_range_yards: 50,
    uses_per_round: "1(3)",
    uses_per_round_int: 3,
    mag: "5",
    mag_int: 5,
    cost: { gaslight: 2400, modern: null },
    malfunction: "96",
    eras: ["gaslight-1890s"],
    category: "Shotguns*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "12-Bore (2B)",
    skill: "Firearms",
    specialization: "Shotgun",
    damage: "4D6/2D6/1D6",
    base_range: "10/20/50 yards",
    base_range_yards: 50,
    uses_per_round: "1 or 2",
    uses_per_round_int: 2,
    mag: "2",
    mag_int: 2,
    cost: { gaslight: 1764, modern: null },
    malfunction: "100",
    eras: ["gaslight-1890s"],
    category: "Shotguns*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "12-Bore Pump-Action",
    skill: "Firearms",
    specialization: "Shotgun",
    damage: "4D6/2D6/1D6",
    base_range: "10/20/50 yards",
    base_range_yards: 50,
    uses_per_round: "1 or 2",
    uses_per_round_int: 2,
    mag: "5",
    mag_int: 5,
    cost: { gaslight: 2400, modern: null },
    malfunction: "96",
    eras: ["gaslight-1890s"],
    category: "Shotguns*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Trench Gun",
    skill: "Firearms",
    specialization: "Shotgun",
    damage: "4D6/2D6/1D6",
    base_range: "10/20/50 yards",
    base_range_yards: 50,
    uses_per_round: "1, 2, or 3",
    uses_per_round_int: 3,
    mag: "5",
    mag_int: 5,
    cost: { gaslight: 2880, modern: null },
    malfunction: "96",
    eras: ["gaslight-1890s"],
    category: "Shotguns*",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "10-Bore",
    skill: "Firearms",
    specialization: "Shotgun",
    damage: "4D6+2/2D6+1/1D4",
    base_range: "10/20/50 yards",
    base_range_yards: 50,
    uses_per_round: "1 or 2",
    uses_per_round_int: 2,
    mag: "2",
    mag_int: 2,
    cost: { gaslight: 3780, modern: null },
    malfunction: "100",
    eras: ["gaslight-1890s"],
    category: "Shotguns*",
    source: { book: "Gaslight Victorian Era", page: null }
  },

  // Table 22: Machine Guns
  {
    name: "Model 1882 Gatling Gun",
    skill: "Firearms",
    specialization: "Machine Gun",
    damage: "2D6+4",
    base_range: "100 yards",
    base_range_yards: 100,
    uses_per_round: "Full auto",
    uses_per_round_int: null,
    mag: "200",
    mag_int: 200,
    cost: { gaslight: 36000, modern: null },
    malfunction: "96",
    eras: ["gaslight-1890s"],
    category: "Machine Guns (i)",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Maxim Gun",
    skill: "Firearms",
    specialization: "Machine Gun",
    damage: "2D6+4",
    base_range: "110 yards",
    base_range_yards: 110,
    uses_per_round: "Full auto",
    uses_per_round_int: null,
    mag: "100 drum/250 belt",
    mag_int: 250,
    cost: { gaslight: 72000, modern: null },
    malfunction: "96",
    eras: ["gaslight-1890s"],
    category: "Machine Guns (i)",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Nordenfelt",
    skill: "Firearms",
    specialization: "Machine Gun",
    damage: "2D6+1",
    base_range: "100 yards",
    base_range_yards: 100,
    uses_per_round: "Full auto",
    uses_per_round_int: null,
    mag: "50 box",
    mag_int: 50,
    cost: { gaslight: 48000, modern: null },
    malfunction: "96",
    eras: ["gaslight-1890s"],
    category: "Machine Guns (i)",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Maxim-Nordenfelt 37mm",
    skill: "Firearms",
    specialization: "Machine Gun",
    damage: "6D6",
    base_range: "200 yards",
    base_range_yards: 200,
    uses_per_round: "Full auto",
    uses_per_round_int: null,
    mag: "100 drum/250 belt",
    mag_int: 250,
    cost: { gaslight: 108000, modern: null },
    malfunction: "96",
    eras: ["gaslight-1890s"],
    category: "Machine Guns (i)",
    source: { book: "Gaslight Victorian Era", page: null }
  },

  // Table 23: Explosives, Heavy Weapons, Misc.
  {
    name: "Incendiary Bottle",
    skill: "Throw",
    specialization: null,
    damage: "2D6+burn",
    base_range: "STR/5 yards",
    base_range_yards: null,
    uses_per_round: "1/2",
    uses_per_round_int: null,
    mag: "—",
    mag_int: null,
    cost: { gaslight: 1, modern: null },
    malfunction: "99",
    eras: ["gaslight-1890s"],
    category: "Explosives, Heavy Weapons, Misc. (i)",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Dynamite Stick",
    skill: "Throw",
    specialization: null,
    damage: "4D10 /3 yards",
    base_range: "STR/5 yards",
    base_range_yards: null,
    uses_per_round: "1/2",
    uses_per_round_int: null,
    mag: "—",
    mag_int: null,
    cost: { gaslight: 5, modern: null },
    malfunction: "98",
    eras: ["gaslight-1890s"],
    category: "Explosives, Heavy Weapons, Misc. (i)",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Nitroglycerin",
    skill: "Demolitions",
    specialization: null,
    damage: "4D10 /3 yards",
    base_range: "In place",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { gaslight: 24, modern: null },
    malfunction: "Luck",
    eras: ["gaslight-1890s"],
    category: "Explosives, Heavy Weapons, Misc. (i)",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Black-Powder Bomb",
    skill: "Demolitions",
    specialization: null,
    damage: "1D10 /3 yards",
    base_range: "In place",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { gaslight: 78, modern: null },
    malfunction: "95",
    eras: ["gaslight-1890s"],
    category: "Explosives, Heavy Weapons, Misc. (i)",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Mysore Rocket",
    skill: "Artillery",
    specialization: "Rocket",
    damage: "4D6 /3 yards",
    base_range: "500 yards",
    base_range_yards: 500,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { gaslight: null, modern: null },
    malfunction: "95",
    eras: ["gaslight-1890s"],
    category: "Explosives, Heavy Weapons, Misc. (i)",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Congreve Rocket 12lb",
    skill: "Artillery",
    specialization: "Rocket",
    damage: "2D6 /3 yards",
    base_range: "650 yards",
    base_range_yards: 650,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { gaslight: null, modern: null },
    malfunction: "95",
    eras: ["gaslight-1890s"],
    category: "Explosives, Heavy Weapons, Misc. (i)",
    source: { book: "Gaslight Victorian Era", page: null }
  },
  {
    name: "Hale Rocket",
    skill: "Artillery",
    specialization: "Rocket",
    damage: "4D10 /3 yards",
    base_range: "650 yards",
    base_range_yards: 650,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { gaslight: null, modern: null },
    malfunction: "96",
    eras: ["gaslight-1890s"],
    category: "Explosives, Heavy Weapons, Misc. (i)",
    source: { book: "Gaslight Victorian Era", page: null }
  }
];

export default WEAPONS_GASLIGHT;