import type { Skill } from '../../types';

export const SKILLS: Skill[] = [
  { name: 'Accounting', base: 10, description: "Basic knowledge of arithmetic and the ability to use an abacus to manage inventories, accounts, and crop registers." },
  { name: 'Animal Handling', base: 15, description: "Command and train animals to perform simple tasks. Essential for livestock, dogs, and working animals. For riding mounts, use the Ride skill instead." },
  { name: 'Appraise', base: 5, description: "Estimate the value of items including quality, materials, and workmanship. Can assess historical relevance and detect forgeries." },
  { name: 'Art and Craft', base: 5, specialty: true, description: "Create works of art or craft items. Medieval specializations include smithing, weaving, carpentry, and other essential trades." },
  { name: 'Charm', base: 15, description: "Influence others through attraction, flattery, or warmth of personality in medieval social settings." },
  { name: 'Climb', base: 20, description: "Scale castle walls, trees, cliffs, and other medieval structures without proper climbing equipment." },
  { name: 'Cthulhu Mythos', base: 0, description: "Forbidden knowledge of cosmic horrors and alien forces. Can only be increased through direct, sanity-shattering experience." },
  { name: 'Dodge', base: 0, description: "Avoid blows and thrown weapons through reflexes and agility. Base value is half of DEX." },
  { name: 'Drive Horses or Oxen', base: 20, description: "Control teams of horses or oxen pulling wagons, carts, or plows. The primary mode of transportation and heavy labor." },
  { name: 'Fast Talk', base: 5, description: "Distract, confuse, or deceive through rapid speech and misdirection in medieval conversations." },
  { name: 'Fighting', base: 25, specialty: true, description: "Engage in medieval combat with various weapons and fighting styles common to the Dark Ages." },
  { name: 'First Aid', base: 30, description: "Provide immediate medical care using medieval methods to stabilize injuries and prevent death." },
  { name: 'Insight', base: 5, description: "Gauge the true motivations and emotional state of others through observation. Crucial in honor-based medieval society." },
  { name: 'Intimidate', base: 15, description: "Compel cooperation through threats, displays of violence, or force of personality in feudal contexts." },
  { name: 'Jump', base: 25, description: "Leap across gaps, over obstacles, or determine damage from falls." },
  { name: 'Library Use', base: 5, description: "Find information in monastery libraries, cathedral archives, and private noble collections. Most books are in Latin." },
  { name: 'Listen', base: 25, description: "Hear faint sounds, eavesdrop on conversations, or detect approaching danger in medieval environments." },
  { name: 'Medicine', base: 1, description: "Practice medieval medicine based on humoral theory, bloodletting, herbal remedies, and prayer." },
  { name: 'Natural World', base: 20, specialty: true, description: "Knowledge of medieval flora, fauna, weather, and survival in natural environments essential to daily life." },
  { name: 'Navigate', base: 10, description: "Find your way using natural landmarks, stars, and crude medieval maps without modern instruments." },
  { name: 'Occult', base: 5, description: "Knowledge of folk magic, witchcraft, alchemy, astrology, and supernatural beliefs of the Dark Ages." },
  { name: 'Other Kingdoms', base: 10, specialty: true, description: "Knowledge of foreign lands, their customs, politics, and peoples beyond your own realm." },
  { name: 'Other Language', base: 1, specialty: true, stub: 'Language', description: "Speak, read, and write in languages other than your native tongue, such as Latin, Greek, or Arabic." },
  { name: 'Own Kingdom', base: 20, description: "Detailed knowledge of your local area including politics, nobles, customs, geography, and current events." },
  { name: 'Own Language', base: 0, description: "Proficiency in your native language. Base value equals EDU. Literacy is rare and valuable in medieval times." },
  { name: 'Persuade', base: 15, description: "Change minds through logical argument, emotional appeal, or skilled rhetoric in medieval discourse." },
  { name: 'Pilot (Boat)', base: 1, description: "Handle and navigate boats and small ships, including knowledge of medieval seamanship and river travel." },
  { name: 'Psychology', base: 10, description: "Understand human motivations and behavior through medieval concepts of temperament and character." },
  { name: 'Ranged Weapons', base: 20, specialty: true, description: "Use medieval ranged weapons such as bows, crossbows, and slings effectively in combat." },
  { name: 'Read and Write', base: 1, specialty: true, description: "Read and write in specific languages. Literacy is a rare and specialized skill in the Dark Ages." },
  { name: 'Religion', base: 20, specialty: true, description: "Knowledge of religious doctrine, practices, and theological matters. Common specializations: Christianity, Islam, Judaism, Norse Paganism, Celtic Paganism, Germanic Paganism." },
  { name: 'Repair/Devise', base: 20, description: "Create, repair, and modify tools, weapons, and simple devices using medieval technology and craftsmanship." },
  { name: 'Ride Horse', base: 5, description: "Ride horses and other mounts, including basic horsemanship and mounted combat. Essential for nobility and warriors." },
  { name: 'Science', base: 1, specialty: true, description: "Knowledge of medieval sciences including alchemy, astronomy, natural philosophy, and primitive medicine." },
  { name: 'Sleight of Hand', base: 25, description: "Perform manual dexterity feats including pickpocketing, palming objects, and simple entertainments." },
  { name: 'Spot Hidden', base: 25, description: "Notice concealed objects, hidden doors, ambushes, or suspicious behavior in medieval settings." },
  { name: 'Status', base: 0, description: "Represents position in the feudal hierarchy from serf to nobility. Determines social power and resources available." },
  { name: 'Stealth', base: 20, description: "Move silently and remain hidden in medieval environments, essential for scouts and those avoiding detection." },
  { name: 'Swim', base: 25, description: "Stay afloat and move through water. Many medieval people cannot swim, making this a valuable skill." },
  { name: 'Throw', base: 25, description: "Accurately throw objects including stones, bottles, and improvised weapons." },
  { name: 'Track', base: 10, description: "Follow trails left by people or animals, determining direction, numbers, and timing of passage." }
];
