// Dark Ages (1000s) Weapons Data
// Based on official Call of Cthulhu Dark Ages sourcebook
// Ordered: Hand-to-Hand → Missile → War Engines → Shields → Armor

export type WeaponRec = {
  name: string;
  skill: string;
  specialization: string | null;
  damage: string;
  base_range: string;
  base_range_yards: number | null;
  uses_per_round: string;
  uses_per_round_int: number | null;
  mag: string;
  mag_int: number | null;
  cost: { darkAges: number | null };
  malfunction: string;
  eras: string[];
  category: string;
  impale: boolean;
  min_str_dex: string | null;
  hands: string;
  length: string | null;
  source: { book: string; page: number | null };
};

export type ShieldRec = {
  name: string;
  armor: string;
  damage: string;
  min_str_dex: string | null;
  cost: { darkAges: number | null };
  category: string;
};

export type ArmorRec = {
  name: string;
  armor: string;
  rounds_to_don: number | null;
  cost: { darkAges: number | null };
  category: string;
};

export const WEAPONS_DARK_AGES: WeaponRec[] = [
  // Hand-to-Hand Weapons
  {
    name: "Unarmed",
    skill: "Fighting",
    specialization: "Brawl",
    damage: "1D3",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { darkAges: null },
    malfunction: "—",
    eras: ["dark-ages-1000s"],
    category: "Hand-to-Hand Weapons",
    impale: false,
    min_str_dex: null,
    hands: "1H or 2H",
    length: null,
    source: { book: "Dark Ages", page: null }
  },
  {
    name: "Axe",
    skill: "Fighting",
    specialization: "Axe",
    damage: "1D6",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { darkAges: 80 },
    malfunction: "—",
    eras: ["dark-ages-1000s"],
    category: "Hand-to-Hand Weapons",
    impale: true,
    min_str_dex: "40/45",
    hands: "1H",
    length: "Medium",
    source: { book: "Dark Ages", page: null }
  },
  {
    name: "Axe, Great",
    skill: "Fighting",
    specialization: "Axe",
    damage: "2D6",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { darkAges: 100 },
    malfunction: "—",
    eras: ["dark-ages-1000s"],
    category: "Hand-to-Hand Weapons",
    impale: true,
    min_str_dex: "55/45",
    hands: "2H",
    length: "Long",
    source: { book: "Dark Ages", page: null }
  },
  {
    name: "Axe, Pick",
    skill: "Fighting",
    specialization: "Axe",
    damage: "2D6",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { darkAges: 90 },
    malfunction: "—",
    eras: ["dark-ages-1000s"],
    category: "Hand-to-Hand Weapons",
    impale: true,
    min_str_dex: "55/45",
    hands: "2H",
    length: "Medium",
    source: { book: "Dark Ages", page: null }
  },
  {
    name: "Club",
    skill: "Fighting",
    specialization: "Brawl",
    damage: "1D6",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { darkAges: null },
    malfunction: "—",
    eras: ["dark-ages-1000s"],
    category: "Hand-to-Hand Weapons",
    impale: false,
    min_str_dex: null,
    hands: "1H",
    length: "Medium",
    source: { book: "Dark Ages", page: null }
  },
  {
    name: "Hammer, Quarry",
    skill: "Fighting",
    specialization: "Mace",
    damage: "2D6",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { darkAges: 80 },
    malfunction: "—",
    eras: ["dark-ages-1000s"],
    category: "Hand-to-Hand Weapons",
    impale: false,
    min_str_dex: "55/45",
    hands: "1H",
    length: "Medium",
    source: { book: "Dark Ages", page: null }
  },
  {
    name: "Flail",
    skill: "Fighting",
    specialization: "Flail",
    damage: "1D6",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { darkAges: 90 },
    malfunction: "—",
    eras: ["dark-ages-1000s"],
    category: "Hand-to-Hand Weapons",
    impale: false,
    min_str_dex: "45/35",
    hands: "1H",
    length: "Medium",
    source: { book: "Dark Ages", page: null }
  },
  {
    name: "Knife, Small",
    skill: "Fighting",
    specialization: "Brawl",
    damage: "1D4",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { darkAges: 10 },
    malfunction: "—",
    eras: ["dark-ages-1000s"],
    category: "Hand-to-Hand Weapons",
    impale: true,
    min_str_dex: null,
    hands: "1H",
    length: "Short",
    source: { book: "Dark Ages", page: null }
  },
  {
    name: "Knife, Large",
    skill: "Fighting",
    specialization: "Brawl",
    damage: "1D6",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { darkAges: 15 },
    malfunction: "—",
    eras: ["dark-ages-1000s"],
    category: "Hand-to-Hand Weapons",
    impale: true,
    min_str_dex: null,
    hands: "1H",
    length: "Short",
    source: { book: "Dark Ages", page: null }
  },
  {
    name: "Lance",
    skill: "Fighting",
    specialization: "Lance",
    damage: "1D8",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { darkAges: 80 },
    malfunction: "—",
    eras: ["dark-ages-1000s"],
    category: "Hand-to-Hand Weapons",
    impale: true,
    min_str_dex: "45/40",
    hands: "1H",
    length: "Long",
    source: { book: "Dark Ages", page: null }
  },
  {
    name: "Mace",
    skill: "Fighting",
    specialization: "Mace",
    damage: "1D6",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { darkAges: 60 },
    malfunction: "—",
    eras: ["dark-ages-1000s"],
    category: "Hand-to-Hand Weapons",
    impale: false,
    min_str_dex: "35/35",
    hands: "1H",
    length: "Medium",
    source: { book: "Dark Ages", page: null }
  },
  {
    name: "Scimitar",
    skill: "Fighting",
    specialization: "Sword",
    damage: "1D8",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { darkAges: null }, // Listed as "Rare"
    malfunction: "—",
    eras: ["dark-ages-1000s"],
    category: "Hand-to-Hand Weapons",
    impale: true,
    min_str_dex: "40/40",
    hands: "1H",
    length: "Medium",
    source: { book: "Dark Ages", page: null }
  },
  {
    name: "Spear, Short",
    skill: "Fighting",
    specialization: "Spear",
    damage: "1D6",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { darkAges: 40 },
    malfunction: "—",
    eras: ["dark-ages-1000s"],
    category: "Hand-to-Hand Weapons",
    impale: true,
    min_str_dex: "35/40",
    hands: "1H",
    length: "Long",
    source: { book: "Dark Ages", page: null }
  },
  {
    name: "Spear, Long",
    skill: "Fighting",
    specialization: "Spear",
    damage: "1D10",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { darkAges: 50 },
    malfunction: "—",
    eras: ["dark-ages-1000s"],
    category: "Hand-to-Hand Weapons",
    impale: true,
    min_str_dex: "55/45",
    hands: "2H",
    length: "Long",
    source: { book: "Dark Ages", page: null }
  },
  {
    name: "Staff",
    skill: "Fighting",
    specialization: "Staff",
    damage: "1D6",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { darkAges: null },
    malfunction: "—",
    eras: ["dark-ages-1000s"],
    category: "Hand-to-Hand Weapons",
    impale: false,
    min_str_dex: "40/30",
    hands: "2H",
    length: "Long",
    source: { book: "Dark Ages", page: null }
  },
  {
    name: "Sword, Short",
    skill: "Fighting",
    specialization: "Sword",
    damage: "1D6",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { darkAges: 150 },
    malfunction: "—",
    eras: ["dark-ages-1000s"],
    category: "Hand-to-Hand Weapons",
    impale: true,
    min_str_dex: "25/25",
    hands: "1H",
    length: "Medium",
    source: { book: "Dark Ages", page: null }
  },
  {
    name: "Sword, Long",
    skill: "Fighting",
    specialization: "Sword",
    damage: "1D8",
    base_range: "Touch",
    base_range_yards: 0,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { darkAges: 210 },
    malfunction: "—",
    eras: ["dark-ages-1000s"],
    category: "Hand-to-Hand Weapons",
    impale: true,
    min_str_dex: "40/35",
    hands: "2H",
    length: "Long",
    source: { book: "Dark Ages", page: null }
  },

  // Missile Weapons
  {
    name: "Axe (Thrown)",
    skill: "Ranged Weapons",
    specialization: "Axe",
    damage: "1D6+½DB",
    base_range: "5 yards",
    base_range_yards: 5,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { darkAges: 80 },
    malfunction: "—",
    eras: ["dark-ages-1000s"],
    category: "Missile Weapons",
    impale: true,
    min_str_dex: "30/30",
    hands: "1H",
    length: null,
    source: { book: "Dark Ages", page: null }
  },
  {
    name: "Axe, Frankish (Thrown)",
    skill: "Ranged Weapons",
    specialization: "Axe",
    damage: "1D6+1+½DB",
    base_range: "STR/5 yards",
    base_range_yards: null,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { darkAges: 100 },
    malfunction: "—",
    eras: ["dark-ages-1000s"],
    category: "Missile Weapons",
    impale: true,
    min_str_dex: "30/30",
    hands: "1H",
    length: null,
    source: { book: "Dark Ages", page: null }
  },
  {
    name: "Bow",
    skill: "Ranged Weapons",
    specialization: "Bow",
    damage: "1D6+½DB",
    base_range: "30 yards",
    base_range_yards: 30,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { darkAges: 60 },
    malfunction: "—",
    eras: ["dark-ages-1000s"],
    category: "Missile Weapons",
    impale: true,
    min_str_dex: "30/40",
    hands: "2H",
    length: null,
    source: { book: "Dark Ages", page: null }
  },
  {
    name: "Crossbow",
    skill: "Ranged Weapons",
    specialization: "Crossbow",
    damage: "1D8+2",
    base_range: "50 yards",
    base_range_yards: 50,
    uses_per_round: "1/2",
    uses_per_round_int: 0.5,
    mag: "—",
    mag_int: null,
    cost: { darkAges: null }, // Listed as "Rare"
    malfunction: "—",
    eras: ["dark-ages-1000s"],
    category: "Missile Weapons",
    impale: true,
    min_str_dex: "30/20",
    hands: "2H",
    length: null,
    source: { book: "Dark Ages", page: null }
  },
  {
    name: "Knife (Thrown)",
    skill: "Fighting",
    specialization: "Brawl",
    damage: "1D4+½DB",
    base_range: "STR/5 yards",
    base_range_yards: null,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { darkAges: 10 },
    malfunction: "—",
    eras: ["dark-ages-1000s"],
    category: "Missile Weapons",
    impale: true,
    min_str_dex: null,
    hands: "1H",
    length: null,
    source: { book: "Dark Ages", page: null }
  },
  {
    name: "Rock",
    skill: "Throw",
    specialization: null,
    damage: "1D2+½DB",
    base_range: "STR/5 yards",
    base_range_yards: null,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { darkAges: null },
    malfunction: "—",
    eras: ["dark-ages-1000s"],
    category: "Missile Weapons",
    impale: false,
    min_str_dex: null,
    hands: "1H",
    length: null,
    source: { book: "Dark Ages", page: null }
  },
  {
    name: "Sling",
    skill: "Ranged Weapons",
    specialization: "Sling",
    damage: "1D4+½DB",
    base_range: "60 yards",
    base_range_yards: 60,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { darkAges: 5 },
    malfunction: "—",
    eras: ["dark-ages-1000s"],
    category: "Missile Weapons",
    impale: false,
    min_str_dex: null,
    hands: "1H",
    length: null,
    source: { book: "Dark Ages", page: null }
  },
  {
    name: "Spear, Short (Thrown)",
    skill: "Ranged Weapons",
    specialization: "Spear",
    damage: "1D8+½DB",
    base_range: "STR/5 yards",
    base_range_yards: null,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { darkAges: 40 },
    malfunction: "—",
    eras: ["dark-ages-1000s"],
    category: "Missile Weapons",
    impale: true,
    min_str_dex: "35/40",
    hands: "1H",
    length: null,
    source: { book: "Dark Ages", page: null }
  },
  {
    name: "Spear, Long (Thrown)",
    skill: "Ranged Weapons",
    specialization: "Spear",
    damage: "1D10+½DB",
    base_range: "STR/5 yards",
    base_range_yards: null,
    uses_per_round: "1",
    uses_per_round_int: 1,
    mag: "—",
    mag_int: null,
    cost: { darkAges: 50 },
    malfunction: "—",
    eras: ["dark-ages-1000s"],
    category: "Missile Weapons",
    impale: true,
    min_str_dex: "40/40",
    hands: "1H",
    length: null,
    source: { book: "Dark Ages", page: null }
  },

  // War Engines
  {
    name: "Ballista",
    skill: "War Engine",
    specialization: null,
    damage: "6D6",
    base_range: "150 yards",
    base_range_yards: 150,
    uses_per_round: "—",
    uses_per_round_int: null,
    mag: "—",
    mag_int: null,
    cost: { darkAges: 400 },
    malfunction: "—",
    eras: ["dark-ages-1000s"],
    category: "War Engines",
    impale: true,
    min_str_dex: null,
    hands: "—",
    length: null,
    source: { book: "Dark Ages", page: null }
  },
  {
    name: "Catapult",
    skill: "War Engine",
    specialization: null,
    damage: "30D6",
    base_range: "100 yards",
    base_range_yards: 100,
    uses_per_round: "—",
    uses_per_round_int: null,
    mag: "—",
    mag_int: null,
    cost: { darkAges: 900 },
    malfunction: "—",
    eras: ["dark-ages-1000s"],
    category: "War Engines",
    impale: false,
    min_str_dex: null,
    hands: "—",
    length: null,
    source: { book: "Dark Ages", page: null }
  },
  {
    name: "Trebuchet, Traction",
    skill: "War Engine",
    specialization: null,
    damage: "4D6",
    base_range: "75 yards",
    base_range_yards: 75,
    uses_per_round: "—",
    uses_per_round_int: null,
    mag: "—",
    mag_int: null,
    cost: { darkAges: 300 },
    malfunction: "—",
    eras: ["dark-ages-1000s"],
    category: "War Engines",
    impale: false,
    min_str_dex: null,
    hands: "—",
    length: null,
    source: { book: "Dark Ages", page: null }
  },
  {
    name: "Trebuchet, Hybrid",
    skill: "War Engine",
    specialization: null,
    damage: "50D6",
    base_range: "50 yards",
    base_range_yards: 50,
    uses_per_round: "—",
    uses_per_round_int: null,
    mag: "—",
    mag_int: null,
    cost: { darkAges: 1500 },
    malfunction: "—",
    eras: ["dark-ages-1000s"],
    category: "War Engines",
    impale: false,
    min_str_dex: null,
    hands: "—",
    length: null,
    source: { book: "Dark Ages", page: null }
  }
];

export const SHIELDS_DARK_AGES: ShieldRec[] = [
  {
    name: "Improvised",
    armor: "1D2 to 1D4",
    damage: "1D2+DB",
    min_str_dex: null,
    cost: { darkAges: null },
    category: "Shields"
  },
  {
    name: "Buckler",
    armor: "1D2",
    damage: "1D2+DB",
    min_str_dex: null,
    cost: { darkAges: 40 },
    category: "Shields"
  },
  {
    name: "Round, Wooden",
    armor: "1D3",
    damage: "1D3+DB",
    min_str_dex: "30/30",
    cost: { darkAges: 60 },
    category: "Shields"
  },
  {
    name: "Round, Viking",
    armor: "1D4",
    damage: "1D4+DB",
    min_str_dex: "40/40",
    cost: { darkAges: 80 },
    category: "Shields"
  },
  {
    name: "Kite",
    armor: "1D4+1",
    damage: "1D4+1+DB",
    min_str_dex: "40/40",
    cost: { darkAges: 80 },
    category: "Shields"
  },
  {
    name: "Tower",
    armor: "1D6",
    damage: "1D4+1+DB",
    min_str_dex: "45/30",
    cost: { darkAges: 100 },
    category: "Shields"
  }
];

export const ARMOR_DARK_AGES: ArmorRec[] = [
  {
    name: "Normal Clothes",
    armor: "0",
    rounds_to_don: null,
    cost: { darkAges: null },
    category: "Armor"
  },
  {
    name: "Heavy Clothes",
    armor: "1D2-1",
    rounds_to_don: 1,
    cost: { darkAges: null },
    category: "Armor"
  },
  {
    name: "Leather, Quilted/Soft",
    armor: "1D2",
    rounds_to_don: 2,
    cost: { darkAges: 50 },
    category: "Armor"
  },
  {
    name: "Leather, Heavy Quilted",
    armor: "1D3",
    rounds_to_don: 2,
    cost: { darkAges: 60 },
    category: "Armor"
  },
  {
    name: "Leather, Boiled",
    armor: "1D6",
    rounds_to_don: 2,
    cost: { darkAges: 100 },
    category: "Armor"
  },
  {
    name: "Leather and Rings",
    armor: "1D6+1",
    rounds_to_don: 2,
    cost: { darkAges: 400 },
    category: "Armor"
  },
  {
    name: "Leather and Scales",
    armor: "1D6+1",
    rounds_to_don: 2,
    cost: { darkAges: 600 },
    category: "Armor"
  },
  {
    name: "Chainmail",
    armor: "1D8",
    rounds_to_don: 4,
    cost: { darkAges: 800 },
    category: "Armor"
  }
];
