import type { EquipmentKit } from '../../types';

// Classic 1920s generic occupational kits. All item names must exist in the
// aggregated ITEMS list for the era (prices + weapons).
export const EQUIPMENT_KITS: EquipmentKit[] = [
  {
    name: "INVESTIGATOR'S FIELD KIT",
    description: 'Comprehensive fieldwork equipment including documentation, navigation, first aid, and climbing capability for typical Call of Cthulhu investigations.',
    items: [
      'Leather Bound Journal',
      'Fountain Pen',
      'Photography Camera',
      'Spare Film (5 rolls)',
      'Portable Typewriter',
      'Compass',
      'Binoculars',
      'Lantern',
      'Flashlight (handheld)',
      'First Aid Kit',
      'Canvas Backpack',
      'Map Case',
      'Field Message Notebook',
      'Canteen',
      'Mess Kit',
      'Rope (50 feet)',
      'Folding Shovel',
      'Folding Pocket Knife',
      '.38 or 9mm Revolver'
    ]
  },
  {
    name: "JOURNALIST'S KIT",
    description: 'Professional reporting equipment with documentation tools, photography, and field mobility essentials.',
    items: [
      'Portable Typewriter',
      'Photography Camera',
      'Spare Film (5 rolls)',
      'Leather Bound Journal',
      'Fountain Pen',
      'Press Credentials',
      'Radio',
      'Compass',
      'Binoculars',
      'Lantern',
      'Flashlight (handheld)',
      'Canvas Backpack',
      'Map Case',
      'Rope (50 feet)',
      'Canteen',
      'Field Message Notebook',
      'Folding Pocket Knife',
      '.32 or 7.65mm Automatic'
    ]
  },
  {
    name: "DOCTOR'S BAG",
    description: 'Professional medical equipment for house calls and field medicine, balanced for both treatment and investigation.',
    items: [
      'Leather Medical Bag',
      'First Aid Kit',
      'Medical Gloves',
      'Stethoscope',
      'Surgical Mask',
      'Medical Scissors',
      'Gauze Dressing',
      'Syringe (set)',
      'Alcohol Swabs',
      'Medical Alcohol',
      'Thermometer',
      'Hemostat',
      'Compass',
      'Binoculars',
      'Rope (25 feet)',
      'Notebook',
      'Folding Pocket Knife',
      '.25 Derringer (1B)'
    ]
  },
  {
    name: 'POLICE CONSTABLE KIT',
    description: 'Complete patrol and investigation equipment for law enforcement, including backup weapon and evidence collection.',
    items: [
      'Police Badge',
      'Handcuffs',
      'Police Whistle',
      'Field Message Notebook',
      'Notepad (spare)',
      'Evidence Bags',
      'Lantern',
      'Compass',
      'Binoculars',
      'Canteen',
      'Map Case',
      'Rope (50 feet)',
      'Folding Shovel',
      'Mess Kit',
      'Folding Pocket Knife',
      'Club, small (nightstick)',
      '.38 or 9mm Revolver',
      '.32 Revolver (backup)'
    ]
  },
  {
    name: "SOLDIER'S FIELD KIT",
    description: 'Complete military field equipment for expeditionary operations, including combat gear, survival tools, and protection.',
    items: [
      '.30-06 Bolt-Action Rifle',
      'Rifle Cleaning Kit',
      'Rifle Sling',
      'Bayonet',
      'Ammo Pouch',
      'Bandolier',
      'Steel Helmet',
      'Gas Mask',
      'Canteen',
      'Canteen Cup',
      'Rucksack',
      'Map Case',
      'Compass',
      'Folding Shovel (Entrenching Tool)',
      'Wire Cutters',
      'Mess Kit',
      'Lantern',
      'Field Knife',
      'First Aid Kit',
      '.45 Automatic (sidearm)'
    ]
  },
  {
    name: "EXPLORER'S EXPEDITION KIT",
    description: 'Comprehensive wilderness expedition gear for extended remote travel, including climbing equipment and emergency medical supplies.',
    items: [
      'Canvas Rucksack',
      'Canvas Tent',
      'Canvas Bedroll',
      'Sleeping Mat',
      'Camping Stove',
      'Camp Lantern',
      'Camp Axe',
      'Machete',
      'Compass',
      'Binoculars',
      'Map Case',
      'Rope (100 feet)',
      'Grappling Hook',
      'Canteen',
      'Mess Kit',
      'Folding Shovel',
      'Folding Camp Chair',
      'Folding Pocket Knife',
      'Bowie Knife',
      'First Aid Kit',
      'First Aid Manual',
      '.30 Lever-Action Carbine'
    ]
  },
  {
    name: "CRIMINAL'S TOOLS",
    description: 'Underworld equipment for breaking and entering, including lockpicks, disguises, and improvised weapons.',
    items: [
      'Lockpick Set',
      'Crowbar (large)',
      'Hand Axe',
      'Utility Knife',
      'Disguise Kit (basic)',
      'Dark Clothing',
      'Lantern (dark)',
      'Flashlight',
      'Leather Gloves',
      'Rope (50 feet)',
      'Canvas Backpack',
      'Binoculars',
      'Compass',
      'Fountain Pen',
      'Leather Bound Journal',
      'Brass Knuckles',
      '.32 or 7.65mm Revolver'
    ]
  },
  {
    name: 'ENGINEER / MECHANIC KIT',
    description: 'Professional mechanical and electrical tools for field repairs, vehicle maintenance, and technical investigations.',
    items: [
      'Tool Outfit (20 tools)',
      'Hand Drill (plus 8 bits)',
      'Rotary Tool Grinder',
      'Wire Cutters',
      'Pliers (multiple types)',
      'Jewelers 48 Piece Tool Set',
      'Padlock',
      'Rope (50 feet)',
      'Light Chain (per foot)',
      'Crowbar',
      'Shovel',
      'Lantern',
      'Compass',
      'Binoculars',
      'Notebook (technical)',
      'Canteen',
      'Folding Pocket Knife',
      '.22 Short Automatic'
    ]
  }
];
