import type { Skill } from '../../types';

export const SKILLS: Skill[] = [
  { name: 'Accounting', base: 5, description: "Track finances, spot irregularities, and create false accounts." },
  { name: 'Anthropology', base: 1, description: "Understand human cultures, behaviors, and beliefs, particularly in primitive or exotic societies." },
  { name: 'Appraise', base: 5, description: "Estimate the value of an item, and spot fakes and forgeries." },
  { name: 'Archaeology', base: 1, description: "Study ancient cultures through their physical remains, artifacts, and ruins." },
  { name: 'Art and Craft', base: 5, specialty: true, description: "Create a work of art or a craft. Can also be used to identify forgeries or repair items." },
  { name: 'Charm', base: 15, description: "Influence others through flattery, wit, and grace. A social skill for making friends and allies." },
  { name: 'Climb', base: 20, description: "Ascend or descend difficult surfaces like walls, trees, or cliffs." },
  { name: 'Credit Rating', base: 0, description: "Represents an investigator's wealth and social standing." },
  { name: 'Cthulhu Mythos', base: 0, description: "Forbidden knowledge of the alien and monstrous forces that lurk at the edge of reality. This skill can only be increased by direct, sanity-shattering experience." },
  { name: 'Disguise', base: 5, description: "Alter one's appearance to be unrecognizable or to impersonate someone else." },
  { name: 'Dodge', base: 0, description: "Automatically avoid a blow or thrown weapon. Base value is half of DEX." },
  { name: 'Drive Auto', base: 20, description: "Operate an automobile, including high-speed chases and difficult maneuvers." },
  { name: 'Electrical Repair', base: 10, description: "Repair or jury-rig electrical devices and systems." },
  { name: 'Fast Talk', base: 5, description: "Convince others with fast, confusing, or plausible-sounding lies. A social skill for deception." },
  { name: 'Fighting', base: 25, specialty: true, description: "Engage in hand-to-hand combat, from simple brawling to mastery of specific melee weapons." },
  { name: 'Firearms', base: 20, specialty: true, description: "Use firearms effectively in combat, from pistols to rifles and shotguns." },
  { name: 'First Aid', base: 30, description: "Provide immediate medical care to stabilize an injury and prevent death." },
  { name: 'History', base: 5, description: "Recall historical events, figures, and contexts." },
  { name: 'Intimidate', base: 15, description: "Influence others through threats, force of personality, or overt menace. A social skill for coercion." },
  { name: 'Jump', base: 20, description: "Leap across gaps or over obstacles." },
  { name: 'Language (Other)', base: 1, specialty: true, stub: 'Language', description: "Speak, read, and write in a language other than your own." },
  { name: 'Language (Own)', base: 0, description: "The investigator's proficiency with their native language. Base value is equal to EDU." },
  { name: 'Law', base: 5, description: "Knowledge of legal procedures, rights, and how to navigate the justice system." },
  { name: 'Library Use', base: 20, description: "Efficiently find information in libraries, archives, and other repositories of records." },
  { name: 'Listen', base: 20, description: "Hear faint or indistinct sounds and interpret their meaning." },
  { name: 'Locksmith', base: 1, description: "Pick locks and bypass physical security." },
  { name: 'Mechanical Repair', base: 10, description: "Repair or jury-rig mechanical devices." },
  { name: 'Medicine', base: 1, description: "Diagnose and treat illnesses and severe injuries. Can perform surgery." },
  { name: 'Natural World', base: 10, description: "Knowledge of flora, fauna, and natural environments." },
  { name: 'Navigate', base: 10, description: "Find your way with or without maps, by stars, or by natural signs." },
  { name: 'Occult', base: 5, description: "Knowledge of fringe beliefs, secret societies, and folklore concerning the supernatural." },
  { name: 'Operate Heavy Machinery', base: 1, description: "Use heavy equipment like a steam shovel, tractor, or industrial machinery." },
  { name: 'Persuade', base: 10, description: "Influence others with reasoned argument, debate, or heartfelt appeal. A social skill for honest conviction." },
  { name: 'Pilot', base: 1, specialty: true, description: "Operate a specific type of complex vehicle, such as an airplane or boat." },
  { name: 'Psychology', base: 10, description: "Understand the motivations and mental state of another person through observation and interaction." },
  { name: 'Psychoanalysis', base: 1, description: "A long-term therapy to help someone recover from mental trauma and lost Sanity." },
  { name: 'Ride', base: 5, description: "Ride and control a mount, such as a horse or camel." },
  { name: 'Science', base: 1, specialty: true, description: "Knowledge in a specific field of science, such as chemistry, physics, or biology." },
  { name: 'Sleight of Hand', base: 10, description: "Perform feats of manual dexterity, such as pickpocketing or palming an object." },
  { name: 'Spot Hidden', base: 25, description: "Notice things that are concealed, overlooked, or out of the ordinary." },
  { name: 'Stealth', base: 20, description: "Move without being seen or heard." },
  { name: 'Survival', base: 10, specialty: true, description: "Survive in a specific type of harsh environment (e.g., Desert, Arctic)." },
  { name: 'Swim', base: 20, description: "Stay afloat and move through water." },
  { name: 'Throw', base: 20, description: "Accurately throw an object." },
  { name: 'Track', base: 10, description: "Follow the tracks of a person or creature." }
];