import type { Occupation } from '../../types';
import { SKILL_SPECIALIZATIONS } from '../../data/skill-specializations-data';

const interpersonal = ['Charm', 'Fast Talk', 'Intimidate', 'Persuade'];
const anySkill = ['*'];

const hobby = (entry: Omit<Occupation, 'group' | 'skillPoints' | 'creditRatingRange'> & { creditRatingRange?: Occupation['creditRatingRange'] }): Occupation => ({
  group: 'Scout Hobby',
  skillPoints: 'Scout rank hobby points',
  creditRatingRange: entry.creditRatingRange || { min: 0, max: 99 },
  ...entry,
});

export const HOBBIES: Occupation[] = [
  hobby({
    name: 'Amateur Sleuth',
    description: 'A mystery-story fan with a magnifying glass, notebook, sharp ears, and a habit of finding trouble.',
    occupationalSkills: ['Law', 'Library Use', 'Stealth', 'Track'],
    choiceGroups: [
      { count: 1, options: interpersonal },
      { count: 1, options: ['Listen', 'Spot Hidden'] },
      { count: 1, options: ['Locksmith', 'Psychology'] },
      { count: 1, options: anySkill },
    ],
    obligations: 'None.',
    trustedAdult: 'Librarian, local historical society, or local reporter.',
    startingBadges: ['Reading Badge'],
  }),
  hobby({
    name: 'Cheerleader',
    description: 'A disciplined and athletic team leader used to training, public attention, and school spirit.',
    occupationalSkills: ['Climb', 'Dodge', 'Jump', 'Throw', 'Spot Hidden'],
    choiceGroups: [{ count: 3, options: anySkill }],
    obligations: 'Training practice and attendance at matches and parades.',
    trustedAdult: 'Sports teacher, coaches, and local sports people.',
    startingBadges: ['Climbing Badge'],
  }),
  hobby({
    name: 'Farmhand',
    description: 'A rural scout used to chores, animals, machines, harvest work, and long days outside.',
    occupationalSkills: ['Art and Craft (Farming)', 'Mechanical Repair', 'Natural World', 'Track'],
    choiceGroups: [
      { count: 1, options: interpersonal },
      { count: 3, options: anySkill },
    ],
    obligations: 'As and when required on the farm.',
    trustedAdult: 'Local farmers, farm workers, and farm supply shops.',
    startingBadges: ['Animal Friendship Badge', 'Fishing Badge', 'Nature Badge'],
  }),
  hobby({
    name: 'Junior Actor',
    description: 'A budding performer with rehearsal discipline, stage confidence, and an instinct for masks.',
    occupationalSkills: ['Art and Craft (Acting)', 'Disguise', 'History', 'Psychology'],
    choiceGroups: [
      { count: 2, options: interpersonal },
      { count: 2, options: anySkill },
    ],
    obligations: 'Regular rehearsals and shows.',
    trustedAdult: 'Drama teacher, local amateur dramatics groups, actors, and patrons.',
    startingBadges: ['Public Speaking Badge'],
  }),
  hobby({
    name: 'Junior Artist',
    description: 'A sketchbook-carrying young artist who notices shapes, maps, colors, and details others miss.',
    occupationalSkills: ['Psychology', 'Spot Hidden'],
    choiceGroups: [
      { count: 1, options: SKILL_SPECIALIZATIONS['Art and Craft'] || ['Drawing'] },
      { count: 1, options: ['History', 'Natural World'] },
      { count: 1, options: interpersonal },
      { count: 1, options: ['Language (French)', 'Language (German)', 'Language (Latin)', 'Language (Spanish)'] },
      { count: 2, options: anySkill },
    ],
    obligations: 'None.',
    trustedAdult: 'Art teacher or local artists.',
    startingBadges: ['Crafting Badge'],
  }),
  hobby({
    name: 'Junior Firefighter',
    description: 'A first-responder hopeful who helps around the fire station and knows how to stay useful in a crisis.',
    occupationalSkills: ['Climb', 'Dodge', 'First Aid', 'Mechanical Repair', 'Spot Hidden'],
    choiceGroups: [{ count: 3, options: anySkill }],
    obligations: 'Regular after-school sessions and occasional community events.',
    trustedAdult: 'Doctors, nurses, local business owners, local clinics, and fire station staff.',
    startingBadges: ['First Aid Badge'],
  }),
  hobby({
    name: 'Junior Musician',
    description: 'A young performer who rehearses, listens closely, and understands the rhythms of a group.',
    occupationalSkills: ['Listen', 'Psychology'],
    choiceGroups: [
      { count: 1, options: SKILL_SPECIALIZATIONS['Art and Craft'] || ['Instrument'] },
      { count: 1, options: interpersonal },
      { count: 4, options: anySkill },
    ],
    obligations: 'Music lessons, performances, practice, and rehearsals.',
    trustedAdult: 'Local musicians and music teacher.',
    startingBadges: ['Ability Badge of Choice'],
  }),
  hobby({
    name: 'Junior Photographer',
    description: 'A camera-carrying scout with an eye for evidence, chemistry, timing, and sneaky angles.',
    occupationalSkills: ['Art and Craft (Photography)', 'Psychology', 'Science (Chemistry)', 'Stealth', 'Spot Hidden'],
    choiceGroups: [
      { count: 1, options: interpersonal },
      { count: 2, options: anySkill },
    ],
    obligations: 'Helping with student yearbook or newspaper.',
    trustedAdult: 'Local newspaper photographer or photography shop owner.',
    startingBadges: ['Photography Badge'],
  }),
  hobby({
    name: 'Junior Police Corps',
    description: 'A scout with parade duty, traffic help, leadership practice, and a positive connection to local law.',
    occupationalSkills: ['Fighting (Brawl)', 'First Aid', 'Law', 'Psychology', 'Spot Hidden'],
    choiceGroups: [
      { count: 1, options: interpersonal },
      { count: 1, options: ['Ride (Bicycle)', 'Drive Auto'] },
      { count: 1, options: anySkill },
    ],
    obligations: 'Regular after-school sessions and occasional public events.',
    trustedAdult: 'Local police officers and small business owners.',
    startingBadges: ['First Aid Badge'],
  }),
  hobby({
    name: 'Junior Sailor',
    description: 'A waterwise scout with knots, swimming, boats, weather, and the habits of lakes or coastlines.',
    occupationalSkills: ['Fighting (Brawl)', 'Navigate', 'Pilot (Boat)', 'Survival', 'Swim'],
    choiceGroups: [
      { count: 1, options: ['Electrical Repair', 'Mechanical Repair'] },
      { count: 2, options: anySkill },
    ],
    obligations: 'Regular after-school sessions and occasional events.',
    trustedAdult: 'Boat owners, fisherfolk, and navy veterans.',
    startingBadges: ['Boating Badge', 'Knot-Tying Badge', 'Weather Badge'],
  }),
  hobby({
    name: 'Library Helper',
    description: 'An organized, literate scout who knows shelves, archives, quiet corners, and how adults file secrets.',
    occupationalSkills: ['Accounting', 'History', 'Language (Own)', 'Library Use', 'Stealth'],
    choiceGroups: [
      { count: 1, options: ['Language (French)', 'Language (German)', 'Language (Latin)', 'Language (Spanish)'] },
      { count: 2, options: anySkill },
    ],
    obligations: 'Regular library shifts.',
    trustedAdult: 'Bookstore owners, local historical society, school librarian, or town librarian.',
    startingBadges: ['Reading Badge'],
  }),
  hobby({
    name: 'Nature Enthusiast',
    description: 'A young naturalist who collects, observes, tracks, listens, and knows the outdoors better than most adults.',
    occupationalSkills: ['Climb', 'Library Use', 'Listen', 'Natural World', 'Spot Hidden', 'Track'],
    choiceGroups: [{ count: 2, options: anySkill }],
    obligations: 'Bird-watching club and nature club.',
    trustedAdult: 'Farmers, local librarians, and park keepers.',
    startingBadges: ['Nature Badge'],
  }),
  hobby({
    name: 'Religious Assistant',
    description: 'A scout connected to a faith community, its rituals, history, adults, and moral responsibilities.',
    occupationalSkills: ['History', 'Library Use', 'Listen', 'Psychology'],
    choiceGroups: [
      { count: 1, options: ['Language (Latin)', 'Language (Hebrew)', 'Language (Greek)', 'Language (Arabic)'] },
      { count: 1, options: interpersonal },
      { count: 2, options: anySkill },
    ],
    obligations: 'Regular worship and community service.',
    trustedAdult: 'Local religious leader and members of the congregation.',
    startingBadges: ['Reading Badge'],
  }),
  hobby({
    name: 'Newspaper Carrier',
    description: 'A bicycle-riding early riser who knows streets, shortcuts, customers, gossip, and morning routines.',
    occupationalSkills: ['Climb', 'Ride (Bicycle)', 'Sleight of Hand', 'Mechanical Repair', 'Natural World', 'Navigate'],
    choiceGroups: [{ count: 2, options: anySkill }],
    obligations: 'Making deliveries every morning.',
    trustedAdult: 'Beat cops, drivers, hobos, and local business owners.',
    startingBadges: ['Cycling Badge'],
  }),
  hobby({
    name: 'Shop Assistant',
    description: 'A part-time helper who learns customers, stockrooms, cash boxes, chores, and the rhythm of town life.',
    occupationalSkills: ['Accounting', 'Listen', 'Psychology', 'Spot Hidden'],
    choiceGroups: [
      { count: 2, options: interpersonal },
      { count: 2, options: anySkill },
    ],
    obligations: 'Regular shifts after school or on Saturdays.',
    trustedAdult: 'Proprietor and regular customers.',
    startingBadges: ['First Aid Badge', 'Reading Badge'],
  }),
  hobby({
    name: 'Sports Prodigy',
    description: 'A gifted athlete with school records, coaches, sore muscles, and a competitive streak.',
    occupationalSkills: ['Climb', 'Dodge', 'Fighting (Brawl)', 'Jump', 'Swim', 'Throw'],
    choiceGroups: [{ count: 2, options: anySkill }],
    obligations: 'Training, practice, and games.',
    trustedAdult: 'College recruiters, high school coaches, local business owners, and sports writers.',
    startingBadges: ['Climbing Badge', 'Cycling Badge', 'Swimming Badge'],
  }),
  hobby({
    name: 'Street Punk',
    description: 'A misunderstood scout with streetwise instincts, risky errands, quick hands, and hard lessons.',
    occupationalSkills: ['Fighting (Brawl)', 'Sleight of Hand', 'Spot Hidden', 'Stealth'],
    choiceGroups: [
      { count: 1, options: ['Art and Craft (Acting)', 'Disguise'] },
      { count: 1, options: ['Charm', 'Fast Talk', 'Intimidate'] },
      { count: 1, options: ['Locksmith', 'Mechanical Repair'] },
      { count: 1, options: anySkill },
    ],
    obligations: 'Running errands and following instructions.',
    trustedAdult: 'Petty criminals or local police trying to help.',
    startingBadges: ['Cycling Badge'],
  }),
  hobby({
    name: 'Young Entrepreneur',
    description: 'A scheme-cooking scout with ledgers, errands, social confidence, and a talent for useful connections.',
    occupationalSkills: ['Accounting', 'Law', 'Library Use', 'Listen', 'Persuade', 'Spot Hidden'],
    choiceGroups: [{ count: 2, options: anySkill }],
    obligations: 'Meeting customers or potential investors.',
    trustedAdult: 'Local businesspeople.',
    startingBadges: ['Reading Badge'],
  }),
  hobby({
    name: 'Young Scientist',
    description: 'A science-club scout with experiments, notebooks, competition projects, and dangerous curiosity.',
    occupationalSkills: ['Library Use', 'Language (Own)'],
    choiceGroups: [
      { count: 2, options: ['Science (Astronomy)', 'Science (Biology)', 'Science (Chemistry)', 'Science (Engineering)', 'Science (Meteorology)', 'Science (Physics)'] },
      { count: 1, options: ['Language (French)', 'Language (German)', 'Language (Latin)', 'Language (Spanish)'] },
      { count: 3, options: anySkill },
    ],
    obligations: 'Science club meetings and occasional events.',
    trustedAdult: 'Local academics, college professors, and science teachers.',
    startingBadges: ['Nature Badge', 'Radio Badge'],
  }),
  hobby({
    name: 'Upstate League',
    description: 'A wealthy scout from a polished networking club, expected to fundraise, impress, and learn how ordinary kids live.',
    occupationalSkills: ['Appraise', 'Language (Own)', 'Ride'],
    choiceGroups: [
      { count: 1, options: SKILL_SPECIALIZATIONS['Art and Craft'] || ['Any'] },
      { count: 1, options: ['Language (French)', 'Language (German)', 'Language (Latin)', 'Language (Spanish)'] },
      { count: 1, options: interpersonal },
      { count: 2, options: anySkill },
    ],
    obligations: 'Extra classes, formal dinners, social functions, fundraising, and internships.',
    trustedAdult: 'Other wealthy families, local political leaders, bankers, and lawyers.',
    startingBadges: ['Ability Badge of Choice'],
    familyCreditRequirement: 'Rich',
    creditRatingRange: { min: 90, max: 99 },
  }),
];

export const OCCUPATIONS = HOBBIES;

